# Sample .bashrc for SuSE Linux
# Copyright (c) SuSE GmbH Nuernberg

# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.
#
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

# Some applications read the EDITOR variable to determine your favourite text
# editor. So uncomment the line below and enter the editor of your choice :-)
#export EDITOR=/usr/bin/vim
#export EDITOR=/usr/bin/mcedit

# For some news readers it makes sense to specify the NEWSSERVER variable here
#export NEWSSERVER=your.news.server

# If you want to use a Palm device with Linux, uncomment the two lines below.
# For some (older) Palm Pilots, you might need to set a lower baud rate
# e.g. 57600 or 38400; lowest is 9600 (very slow!)
#
#export PILOTPORT=/dev/pilot
#export PILOTRATE=115200

test -s ~/.alias && . ~/.alias || true

alias panic='cd ${PAPI_HOME}'
alias data='cd /data1/'


### PAPI environment ###
##
export CAMHOME=${HOME}/GEIRS
export PAPI_HOME=${HOME}/DEVELOP/papi
PYTHONPATH=$PYTHONPATH:$PAPI_HOME
PAPI_CONFIG=$PAPI_HOME/config_files/papi_panic2_PANIC.cfg
PAPI_PROD=/data2/out
# Proxy required for cdsclient at MPIA
http_proxy=derfel.caha.es:3128
export PYTHONPATH PAPI_HOME PAPI_CONFIG http_proxy

# PANIC-MIDAS PROCEDURES
GEIRSLSTABORT="/home/panic/GEIRS/geirsLstAbort"
CA_FFLTEST=$PAPI_HOME/simu/caha/ffltest
AUPLAY=/usr/bin/play
GEIRS_DIR=/home/panic/GEIRS
FLAT_COMMAND=$PAPI_HOME/simu/caha/flats
TECS_SCRIPT=$HOME/TECS/scripts
PANIC_UTIL=$PAPI_HOME/MIDAS
PANIC_SCI=$PAPI_HOME/MIDAS
ASTROMETRY=/usr/local/astrometry/bin

PATH=$PATH:$HOME/GEIRS/scripts:$HOME/GEIRS/binrjm:$ASTROMETRY:$HOME/bin:$HOME/TECS/scripts
export GEIRSLSTABORT CA_FFLTEST AUPLAY GEIRS_DIR FLAT_COMMAND TECS_SCRIPT PANIC_UTIL PANIC_SCI

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64
export LD_LIBRARY_PATH
export QT_GRAPHICSSYSTEM=native

### OT environment ###
export _JAVA_OPTIONS='-Dhttp.proxyHost=derfel.caha.es -Dhttp.proxyPort=3128'
### end OT environment ###

