# Sample .bashrc for PANIC software

test -s ~/.alias && . ~/.alias || true

alias panic='cd ${PAPI_HOME}'
alias data='cd /data1/PANIC'

### GEIRS environment ###
###
# In case the operator has already set TELESCOPE in the shell,
# GEIRS accept this. Otherwise, the operator must select on the
# GEIRS init window the right telescope. 
# Note: It does not move the cold stop.
if [[ $HOST =~ panic22 ]] ; then
    export TELESCOPE="CA2.2m"
elif [[ $HOST =~ panic35 ]] ; then
    export TELESCOPE="CA3.5m"
fi

export CAMHOME=${HOME}/GEIRS
TECS_SCRIPT=$HOME/TECS/scripts

### PAPI environment ###
##
PAPI_HOME=${HOME}/papi
PYTHONPATH=$PYTHONPATH:$PAPI_HOME
PAPI_CONFIG=$PAPI_HOME/config_files/papi.cfg
QT_GRAPHICSSYSTEM=native
ASTROMETRY=/usr/local/astrometry/bin

# Proxy required for cdsclient at MPIA
if [[ ($HOST =~ panic22) || ($HOST =~ panic35) ]] ; then
    export http_proxy=derfel.caha.es:3128
fi

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64
MONTAGE=$HOME/Montage_v3.3/bin
PATH=$PATH:$HOME/GEIRS/scripts:$HOME/GEIRS/binrjm:$ASTROMETRY:$HOME/bin:$HOME/TECS/scripts:$MONTAGE

export PYTHONPATH PAPI_HOME PAPI_CONFIG http_proxy ASTROMETRY
export TECS_SCRIPT LD_LIBRARY_PATH QT_GRAPHICSSYSTEM PATH


### OT environment ###
export _JAVA_OPTIONS='-Dhttp.proxyHost=derfel.caha.es -Dhttp.proxyPort=3128'
export TELE_REL_MAX_OFFSET='10000'
### end OT environment ###

### Para enviar el sonido al SOR (terminal) del 2.2m/3.5m
if [[ $HOST =~ panic22 ]] ; then
    export AUDIOSERVER="xt22:0"
elif [[ $HOST =~ panic35 ]] ; then
    export AUDIOSERVER="xt32:0"
fi
###

