DEFI/PAR P1 ? C "input file a =?"
DEFI/PAR P2 ? C "input file b =?"
DEFI/PAR P3 ? C "output file=?"
DEFI/PAR P4 ? N "size of output file=?"
DEFI/PAR P5 10,0 N "X/Y SHIFT FILE A = ?"
DEFI/PAR P6 638,0 N "X/Y SHIFT FILE B = ?"
WRITE/KEYW IN_A/C/1/20 'P1'
WRITE/KEYW IN_B/C/1/20 'P2'
WRITE/KEYW OUT_A/C/1/20 'P3'
WRITE/KEYW INPUTI/I/1/2 'P4'
WRITE/KEYW INPUTI/I/3/4 'P5'
WRITE/KEYW INPUTI/I/5/6 'P6'
RUN FM:FUDGE
