# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panicQL.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_panicQL(object):
    def setupUi(self, panicQL):
        panicQL.setObjectName("panicQL")
        panicQL.resize(961, 729)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/my_icon/images/logo_PANIC_100.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        panicQL.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(panicQL)
        self.widget.setObjectName("widget")
        self.textLabel1_7_2 = QtWidgets.QLabel(self.widget)
        self.textLabel1_7_2.setGeometry(QtCore.QRect(14, 458, 220, 22))
        self.textLabel1_7_2.setWordWrap(False)
        self.textLabel1_7_2.setObjectName("textLabel1_7_2")
        self.tabWidget3 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget3.setEnabled(True)
        self.tabWidget3.setGeometry(QtCore.QRect(10, 0, 940, 460))
        self.tabWidget3.setObjectName("tabWidget3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox_autocheck = QtWidgets.QCheckBox(self.tab)
        self.checkBox_autocheck.setGeometry(QtCore.QRect(440, 31, 20, 20))
        self.checkBox_autocheck.setText("")
        self.checkBox_autocheck.setChecked(False)
        self.checkBox_autocheck.setObjectName("checkBox_autocheck")
        self.checkBox_outDir_autocheck = QtWidgets.QCheckBox(self.tab)
        self.checkBox_outDir_autocheck.setGeometry(QtCore.QRect(441, 64, 20, 20))
        self.checkBox_outDir_autocheck.setText("")
        self.checkBox_outDir_autocheck.setObjectName("checkBox_outDir_autocheck")
        self.textLabel1_3 = QtWidgets.QLabel(self.tab)
        self.textLabel1_3.setGeometry(QtCore.QRect(430, 10, 50, 20))
        self.textLabel1_3.setWordWrap(False)
        self.textLabel1_3.setObjectName("textLabel1_3")
        self.pushButton_remove = QtWidgets.QPushButton(self.tab)
        self.pushButton_remove.setGeometry(QtCore.QRect(755, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.pushButton_add = QtWidgets.QPushButton(self.tab)
        self.pushButton_add.setGeometry(QtCore.QRect(671, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pixmapLabel1_2 = QtWidgets.QLabel(self.tab)
        self.pixmapLabel1_2.setGeometry(QtCore.QRect(767, 25, 81, 71))
        self.pixmapLabel1_2.setPixmap(QtGui.QPixmap("../../../.designer/backup/images/logo_PANIC.jpg"))
        self.pixmapLabel1_2.setScaledContents(True)
        self.pixmapLabel1_2.setWordWrap(False)
        self.pixmapLabel1_2.setObjectName("pixmapLabel1_2")
        self.pushButton_clear = QtWidgets.QPushButton(self.tab)
        self.pushButton_clear.setGeometry(QtCore.QRect(843, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.textLabel2_3 = QtWidgets.QLabel(self.tab)
        self.textLabel2_3.setGeometry(QtCore.QRect(10, 390, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel2_3.setFont(font)
        self.textLabel2_3.setWordWrap(False)
        self.textLabel2_3.setObjectName("textLabel2_3")
        self.lineEdit_last_file = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_last_file.setGeometry(QtCore.QRect(140, 390, 311, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_last_file.setPalette(palette)
        self.lineEdit_last_file.setReadOnly(True)
        self.lineEdit_last_file.setObjectName("lineEdit_last_file")
        self.pushButton_dataSourceD = QtWidgets.QPushButton(self.tab)
        self.pushButton_dataSourceD.setGeometry(QtCore.QRect(19, 27, 110, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dataSourceD.setFont(font)
        self.pushButton_dataSourceD.setObjectName("pushButton_dataSourceD")
        self.lineEdit_outputD = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_outputD.setGeometry(QtCore.QRect(141, 63, 290, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_outputD.setPalette(palette)
        self.lineEdit_outputD.setReadOnly(True)
        self.lineEdit_outputD.setObjectName("lineEdit_outputD")
        self.pushButton_outputD = QtWidgets.QPushButton(self.tab)
        self.pushButton_outputD.setGeometry(QtCore.QRect(19, 61, 110, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_outputD.setFont(font)
        self.pushButton_outputD.setObjectName("pushButton_outputD")
        self.pushButton_file_filter = QtWidgets.QPushButton(self.tab)
        self.pushButton_file_filter.setGeometry(QtCore.QRect(609, 30, 131, 23))
        self.pushButton_file_filter.setObjectName("pushButton_file_filter")
        self.pushButton_createCalibs = QtWidgets.QPushButton(self.tab)
        self.pushButton_createCalibs.setGeometry(QtCore.QRect(770, 110, 140, 23))
        self.pushButton_createCalibs.setObjectName("pushButton_createCalibs")
        self.textLabel4_2_3 = QtWidgets.QLabel(self.tab)
        self.textLabel4_2_3.setGeometry(QtCore.QRect(20, 150, 110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2_3.setFont(font)
        self.textLabel4_2_3.setWordWrap(False)
        self.textLabel4_2_3.setObjectName("textLabel4_2_3")
        self.textLabel4_2 = QtWidgets.QLabel(self.tab)
        self.textLabel4_2.setGeometry(QtCore.QRect(18, 101, 110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2.setFont(font)
        self.textLabel4_2.setWordWrap(False)
        self.textLabel4_2.setObjectName("textLabel4_2")
        self.comboBox_classFilter = QtWidgets.QComboBox(self.tab)
        self.comboBox_classFilter.setGeometry(QtCore.QRect(18, 121, 121, 21))
        self.comboBox_classFilter.setObjectName("comboBox_classFilter")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_classFilter.addItem("")
        self.comboBox_QL_Mode = QtWidgets.QComboBox(self.tab)
        self.comboBox_QL_Mode.setGeometry(QtCore.QRect(183, 121, 110, 21))
        self.comboBox_QL_Mode.setObjectName("comboBox_QL_Mode")
        self.comboBox_QL_Mode.addItem("")
        self.comboBox_QL_Mode.addItem("")
        self.comboBox_QL_Mode.addItem("")
        self.comboBox_QL_Mode.addItem("")
        self.comboBox_QL_Mode.addItem("")
        self.comboBox_QL_Mode.addItem("")
        self.textLabel4_2_2 = QtWidgets.QLabel(self.tab)
        self.textLabel4_2_2.setGeometry(QtCore.QRect(189, 100, 80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2_2.setFont(font)
        self.textLabel4_2_2.setWordWrap(False)
        self.textLabel4_2_2.setObjectName("textLabel4_2_2")
        self.pushButton_start_proc = QtWidgets.QPushButton(self.tab)
        self.pushButton_start_proc.setGeometry(QtCore.QRect(770, 140, 140, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_start_proc.setPalette(palette)
        self.pushButton_start_proc.setObjectName("pushButton_start_proc")
        self.pushButton_subtract_last2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_subtract_last2.setGeometry(QtCore.QRect(650, 139, 111, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_subtract_last2.setPalette(palette)
        self.pushButton_subtract_last2.setObjectName("pushButton_subtract_last2")
        self.lineEdit_sourceD = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_sourceD.setGeometry(QtCore.QRect(140, 30, 290, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_sourceD.setPalette(palette)
        self.lineEdit_sourceD.setReadOnly(True)
        self.lineEdit_sourceD.setObjectName("lineEdit_sourceD")
        self.lineEdit_filename_filter = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_filename_filter.setGeometry(QtCore.QRect(475, 30, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_filename_filter.setPalette(palette)
        self.lineEdit_filename_filter.setAlignment(QtCore.Qt.AlignRight)
        self.lineEdit_filename_filter.setReadOnly(True)
        self.lineEdit_filename_filter.setObjectName("lineEdit_filename_filter")
        self.listView_dataS = QtWidgets.QTreeWidget(self.tab)
        self.listView_dataS.setGeometry(QtCore.QRect(10, 170, 911, 211))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.listView_dataS.setPalette(palette)
        self.listView_dataS.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listView_dataS.setObjectName("listView_dataS")
        self.listView_dataS.header().setDefaultSectionSize(50)
        self.listView_dataS.header().setHighlightSections(False)
        self.listView_dataS.header().setMinimumSectionSize(20)
        self.listView_dataS.header().setStretchLastSection(True)
        self.lineEdit_queue_size = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_queue_size.setGeometry(QtCore.QRect(536, 64, 60, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_queue_size.setPalette(palette)
        self.lineEdit_queue_size.setAlignment(QtCore.Qt.AlignRight)
        self.lineEdit_queue_size.setReadOnly(True)
        self.lineEdit_queue_size.setObjectName("lineEdit_queue_size")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(605, 65, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(810, 20, 91, 71))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(84, 84))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.checkBox_geirsFile = QtWidgets.QCheckBox(self.tab)
        self.checkBox_geirsFile.setGeometry(QtCore.QRect(140, 10, 20, 20))
        self.checkBox_geirsFile.setText("")
        self.checkBox_geirsFile.setChecked(False)
        self.checkBox_geirsFile.setObjectName("checkBox_geirsFile")
        self.textLabel1_5 = QtWidgets.QLabel(self.tab)
        self.textLabel1_5.setGeometry(QtCore.QRect(160, 10, 91, 20))
        self.textLabel1_5.setWordWrap(False)
        self.textLabel1_5.setObjectName("textLabel1_5")
        self.checkBox_currentNight = QtWidgets.QCheckBox(self.tab)
        self.checkBox_currentNight.setGeometry(QtCore.QRect(275, 10, 20, 20))
        self.checkBox_currentNight.setText("")
        self.checkBox_currentNight.setChecked(False)
        self.checkBox_currentNight.setObjectName("checkBox_currentNight")
        self.textLabel1_6 = QtWidgets.QLabel(self.tab)
        self.textLabel1_6.setGeometry(QtCore.QRect(295, 10, 101, 20))
        self.textLabel1_6.setWordWrap(False)
        self.textLabel1_6.setObjectName("textLabel1_6")
        self.tabWidget3.addTab(self.tab, "")
        self.TabPage = QtWidgets.QWidget()
        self.TabPage.setObjectName("TabPage")
        self.groupBox = QtWidgets.QGroupBox(self.TabPage)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 271, 131))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox7_2_2_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox7_2_2_2.setChecked(True)
        self.checkBox7_2_2_2.setObjectName("checkBox7_2_2_2")
        self.verticalLayout_2.addWidget(self.checkBox7_2_2_2)
        self.pushButton_tempD = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_tempD.setObjectName("pushButton_tempD")
        self.verticalLayout_2.addWidget(self.pushButton_tempD)
        self.lineEdit_tempD = QtWidgets.QLineEdit(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_tempD.setPalette(palette)
        self.lineEdit_tempD.setReadOnly(True)
        self.lineEdit_tempD.setObjectName("lineEdit_tempD")
        self.verticalLayout_2.addWidget(self.lineEdit_tempD)
        self.groupBox_2 = QtWidgets.QGroupBox(self.TabPage)
        self.groupBox_2.setGeometry(QtCore.QRect(311, 10, 281, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textLabel5 = QtWidgets.QLabel(self.groupBox_2)
        self.textLabel5.setGeometry(QtCore.QRect(192, 22, 58, 20))
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.textLabel5_2 = QtWidgets.QLabel(self.groupBox_2)
        self.textLabel5_2.setGeometry(QtCore.QRect(192, 45, 58, 20))
        self.textLabel5_2.setMidLineWidth(1)
        self.textLabel5_2.setWordWrap(False)
        self.textLabel5_2.setObjectName("textLabel5_2")
        self.checkBox_data_grouping_OT = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_data_grouping_OT.setGeometry(QtCore.QRect(14, 103, 140, 19))
        self.checkBox_data_grouping_OT.setChecked(False)
        self.checkBox_data_grouping_OT.setObjectName("checkBox_data_grouping_OT")
        self.textLabel5_3 = QtWidgets.QLabel(self.groupBox_2)
        self.textLabel5_3.setGeometry(QtCore.QRect(192, 70, 58, 20))
        self.textLabel5_3.setMidLineWidth(1)
        self.textLabel5_3.setWordWrap(False)
        self.textLabel5_3.setObjectName("textLabel5_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 93, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textLabel4_3 = QtWidgets.QLabel(self.layoutWidget)
        self.textLabel4_3.setWordWrap(False)
        self.textLabel4_3.setObjectName("textLabel4_3")
        self.verticalLayout_3.addWidget(self.textLabel4_3)
        self.textLabel4_3_2 = QtWidgets.QLabel(self.layoutWidget)
        self.textLabel4_3_2.setWordWrap(False)
        self.textLabel4_3_2.setObjectName("textLabel4_3_2")
        self.verticalLayout_3.addWidget(self.textLabel4_3_2)
        self.textLabel4_3_3 = QtWidgets.QLabel(self.layoutWidget)
        self.textLabel4_3_3.setWordWrap(False)
        self.textLabel4_3_3.setObjectName("textLabel4_3_3")
        self.verticalLayout_3.addWidget(self.textLabel4_3_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 20, 61, 76))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_ra_dec_near_offset = QtWidgets.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_ra_dec_near_offset.setPalette(palette)
        self.lineEdit_ra_dec_near_offset.setObjectName("lineEdit_ra_dec_near_offset")
        self.verticalLayout_4.addWidget(self.lineEdit_ra_dec_near_offset)
        self.lineEdit_time_near_offset = QtWidgets.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_time_near_offset.setPalette(palette)
        self.lineEdit_time_near_offset.setObjectName("lineEdit_time_near_offset")
        self.verticalLayout_4.addWidget(self.lineEdit_time_near_offset)
        self.lineEdit_max_num_files = QtWidgets.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_max_num_files.setPalette(palette)
        self.lineEdit_max_num_files.setObjectName("lineEdit_max_num_files")
        self.verticalLayout_4.addWidget(self.lineEdit_max_num_files)
        self.groupBox_3 = QtWidgets.QGroupBox(self.TabPage)
        self.groupBox_3.setGeometry(QtCore.QRect(610, 10, 301, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_AstromCatalog = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_AstromCatalog.setGeometry(QtCore.QRect(17, 40, 90, 21))
        self.comboBox_AstromCatalog.setObjectName("comboBox_AstromCatalog")
        self.comboBox_AstromCatalog.addItem("")
        self.comboBox_AstromCatalog.addItem("")
        self.comboBox_AstromCatalog.addItem("")
        self.comboBox_AstromCatalog.addItem("")
        self.comboBox_AstromCatalog.addItem("")
        self.comboBox_AstromCatalog.addItem("")
        self.textLabel1_2 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel1_2.setGeometry(QtCore.QRect(17, 20, 58, 20))
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.textLabel3_4 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel3_4.setGeometry(QtCore.QRect(20, 70, 161, 16))
        self.textLabel3_4.setWordWrap(False)
        self.textLabel3_4.setObjectName("textLabel3_4")
        self.comboBox_AstromEngine = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_AstromEngine.setGeometry(QtCore.QRect(19, 90, 161, 21))
        self.comboBox_AstromEngine.setObjectName("comboBox_AstromEngine")
        self.comboBox_AstromEngine.addItem("")
        self.comboBox_AstromEngine.addItem("")
        self.line_edit_detect_threshold = QtWidgets.QLineEdit(self.groupBox_3)
        self.line_edit_detect_threshold.setGeometry(QtCore.QRect(225, 40, 59, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.line_edit_detect_threshold.setPalette(palette)
        self.line_edit_detect_threshold.setObjectName("line_edit_detect_threshold")
        self.textLabel4_4 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel4_4.setGeometry(QtCore.QRect(180, 20, 111, 20))
        self.textLabel4_4.setWordWrap(False)
        self.textLabel4_4.setObjectName("textLabel4_4")
        self.groupBox_LazyMode = QtWidgets.QGroupBox(self.TabPage)
        self.groupBox_LazyMode.setGeometry(QtCore.QRect(20, 251, 271, 171))
        self.groupBox_LazyMode.setObjectName("groupBox_LazyMode")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_LazyMode)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_subDark_FF_BPM = QtWidgets.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subDark_FF_BPM.setChecked(False)
        self.checkBox_subDark_FF_BPM.setAutoExclusive(True)
        self.checkBox_subDark_FF_BPM.setObjectName("checkBox_subDark_FF_BPM")
        self.verticalLayout.addWidget(self.checkBox_subDark_FF_BPM)
        self.checkBox_subLastFrame = QtWidgets.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subLastFrame.setAutoExclusive(True)
        self.checkBox_subLastFrame.setObjectName("checkBox_subLastFrame")
        self.verticalLayout.addWidget(self.checkBox_subLastFrame)
        self.checkBox_subSky = QtWidgets.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subSky.setEnabled(True)
        self.checkBox_subSky.setAutoExclusive(True)
        self.checkBox_subSky.setObjectName("checkBox_subSky")
        self.verticalLayout.addWidget(self.checkBox_subSky)
        self.groupBox_PrereductionMode = QtWidgets.QGroupBox(self.TabPage)
        self.groupBox_PrereductionMode.setGeometry(QtCore.QRect(310, 152, 601, 271))
        self.groupBox_PrereductionMode.setObjectName("groupBox_PrereductionMode")
        self.comboBox_pre_skyWindow = QtWidgets.QComboBox(self.groupBox_PrereductionMode)
        self.comboBox_pre_skyWindow.setGeometry(QtCore.QRect(30, 190, 118, 21))
        self.comboBox_pre_skyWindow.setObjectName("comboBox_pre_skyWindow")
        self.comboBox_pre_skyWindow.addItem("")
        self.comboBox_pre_skyWindow.addItem("")
        self.comboBox_pre_skyWindow.addItem("")
        self.comboBox_pre_skyWindow.addItem("")
        self.comboBox_pre_skyWindow.addItem("")
        self.checkBox_pre_QM = QtWidgets.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_QM.setEnabled(False)
        self.checkBox_pre_QM.setGeometry(QtCore.QRect(260, 70, 311, 19))
        self.checkBox_pre_QM.setChecked(True)
        self.checkBox_pre_QM.setObjectName("checkBox_pre_QM")
        self.textLabel3 = QtWidgets.QLabel(self.groupBox_PrereductionMode)
        self.textLabel3.setGeometry(QtCore.QRect(30, 170, 151, 16))
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.checkBox_pre_MA = QtWidgets.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_MA.setEnabled(False)
        self.checkBox_pre_MA.setGeometry(QtCore.QRect(260, 40, 180, 19))
        self.checkBox_pre_MA.setChecked(True)
        self.checkBox_pre_MA.setObjectName("checkBox_pre_MA")
        self.checkBox_pre_appBPM = QtWidgets.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appBPM.setGeometry(QtCore.QRect(30, 100, 180, 19))
        self.checkBox_pre_appBPM.setChecked(False)
        self.checkBox_pre_appBPM.setObjectName("checkBox_pre_appBPM")
        self.checkBox_pre_subDark_FF = QtWidgets.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_subDark_FF.setGeometry(QtCore.QRect(30, 40, 180, 19))
        self.checkBox_pre_subDark_FF.setChecked(False)
        self.checkBox_pre_subDark_FF.setObjectName("checkBox_pre_subDark_FF")
        self.checkBox_pre_appSF = QtWidgets.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appSF.setGeometry(QtCore.QRect(30, 70, 180, 19))
        self.checkBox_pre_appSF.setChecked(True)
        self.checkBox_pre_appSF.setObjectName("checkBox_pre_appSF")
        self.checkBox_pre_BS = QtWidgets.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_BS.setEnabled(False)
        self.checkBox_pre_BS.setGeometry(QtCore.QRect(260, 100, 171, 19))
        self.checkBox_pre_BS.setChecked(True)
        self.checkBox_pre_BS.setObjectName("checkBox_pre_BS")
        self.checkBox_pre_appNLC = QtWidgets.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appNLC.setGeometry(QtCore.QRect(30, 130, 181, 19))
        self.checkBox_pre_appNLC.setChecked(False)
        self.checkBox_pre_appNLC.setObjectName("checkBox_pre_appNLC")
        self.comboBox_detector = QtWidgets.QComboBox(self.groupBox_PrereductionMode)
        self.comboBox_detector.setGeometry(QtCore.QRect(200, 190, 118, 21))
        self.comboBox_detector.setObjectName("comboBox_detector")
        self.comboBox_detector.addItem("")
        self.comboBox_detector.addItem("")
        self.comboBox_detector.addItem("")
        self.comboBox_detector.addItem("")
        self.comboBox_detector.addItem("")
        self.comboBox_detector.addItem("")
        self.textLabel3_3 = QtWidgets.QLabel(self.groupBox_PrereductionMode)
        self.textLabel3_3.setGeometry(QtCore.QRect(200, 170, 151, 16))
        self.textLabel3_3.setWordWrap(False)
        self.textLabel3_3.setObjectName("textLabel3_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.TabPage)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 150, 271, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_show_imgs = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_show_imgs.setGeometry(QtCore.QRect(30, 30, 211, 22))
        self.comboBox_show_imgs.setObjectName("comboBox_show_imgs")
        self.comboBox_show_imgs.addItem("")
        self.comboBox_show_imgs.addItem("")
        self.comboBox_show_imgs.addItem("")
        self.comboBox_show_imgs.addItem("")
        self.tabWidget3.addTab(self.TabPage, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setObjectName("tab1")
        self.textLabel3_2 = QtWidgets.QLabel(self.tab1)
        self.textLabel3_2.setGeometry(QtCore.QRect(701, 140, 61, 20))
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName("textLabel3_2")
        self.pushButton_loadLastCalibs = QtWidgets.QPushButton(self.tab1)
        self.pushButton_loadLastCalibs.setEnabled(True)
        self.pushButton_loadLastCalibs.setGeometry(QtCore.QRect(23, 66, 141, 29))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 152, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 126, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 67, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 178, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 152, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 126, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 67, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 178, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 152, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 126, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 67, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_loadLastCalibs.setPalette(palette)
        self.pushButton_loadLastCalibs.setStatusTip("")
        self.pushButton_loadLastCalibs.setObjectName("pushButton_loadLastCalibs")
        self.pushButton_test1 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_test1.setEnabled(False)
        self.pushButton_test1.setGeometry(QtCore.QRect(800, 40, 108, 23))
        self.pushButton_test1.setObjectName("pushButton_test1")
        self.checkBox_use_defCalibs = QtWidgets.QCheckBox(self.tab1)
        self.checkBox_use_defCalibs.setGeometry(QtCore.QRect(172, 73, 121, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_use_defCalibs.setFont(font)
        self.checkBox_use_defCalibs.setObjectName("checkBox_use_defCalibs")
        self.textLabel3_5 = QtWidgets.QLabel(self.tab1)
        self.textLabel3_5.setGeometry(QtCore.QRect(700, 116, 61, 20))
        self.textLabel3_5.setWordWrap(False)
        self.textLabel3_5.setObjectName("textLabel3_5")
        self.textLabel3_6 = QtWidgets.QLabel(self.tab1)
        self.textLabel3_6.setGeometry(QtCore.QRect(702, 198, 111, 20))
        self.textLabel3_6.setWordWrap(False)
        self.textLabel3_6.setObjectName("textLabel3_6")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab1)
        self.layoutWidget2.setGeometry(QtCore.QRect(173, 111, 401, 119))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_masterDark = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterDark.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_masterDark.setPalette(palette)
        self.lineEdit_masterDark.setReadOnly(True)
        self.lineEdit_masterDark.setObjectName("lineEdit_masterDark")
        self.verticalLayout_5.addWidget(self.lineEdit_masterDark)
        self.lineEdit_masterFlat = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterFlat.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_masterFlat.setPalette(palette)
        self.lineEdit_masterFlat.setReadOnly(True)
        self.lineEdit_masterFlat.setObjectName("lineEdit_masterFlat")
        self.verticalLayout_5.addWidget(self.lineEdit_masterFlat)
        self.lineEdit_masterMask = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterMask.setEnabled(False)
        self.lineEdit_masterMask.setReadOnly(True)
        self.lineEdit_masterMask.setObjectName("lineEdit_masterMask")
        self.verticalLayout_5.addWidget(self.lineEdit_masterMask)
        self.lineEdit_masterNLC = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterNLC.setEnabled(False)
        self.lineEdit_masterNLC.setReadOnly(True)
        self.lineEdit_masterNLC.setObjectName("lineEdit_masterNLC")
        self.verticalLayout_5.addWidget(self.lineEdit_masterNLC)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab1)
        self.layoutWidget3.setGeometry(QtCore.QRect(23, 109, 141, 125))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_master_dark = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_master_dark.setEnabled(True)
        self.pushButton_master_dark.setObjectName("pushButton_master_dark")
        self.verticalLayout_6.addWidget(self.pushButton_master_dark)
        self.pushButton_master_flat = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_master_flat.setEnabled(True)
        self.pushButton_master_flat.setObjectName("pushButton_master_flat")
        self.verticalLayout_6.addWidget(self.pushButton_master_flat)
        self.pushButton_master_mask = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_master_mask.setEnabled(True)
        self.pushButton_master_mask.setObjectName("pushButton_master_mask")
        self.verticalLayout_6.addWidget(self.pushButton_master_mask)
        self.pushButton_master_nlc = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_master_nlc.setEnabled(True)
        self.pushButton_master_nlc.setObjectName("pushButton_master_nlc")
        self.verticalLayout_6.addWidget(self.pushButton_master_nlc)
        self.textLabel3_7 = QtWidgets.QLabel(self.tab1)
        self.textLabel3_7.setGeometry(QtCore.QRect(703, 171, 51, 18))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel3_7.setFont(font)
        self.textLabel3_7.setWordWrap(False)
        self.textLabel3_7.setObjectName("textLabel3_7")
        self.lineEdit_calibsD = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_calibsD.setGeometry(QtCore.QRect(174, 24, 401, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_calibsD.setPalette(palette)
        self.lineEdit_calibsD.setReadOnly(True)
        self.lineEdit_calibsD.setObjectName("lineEdit_calibsD")
        self.pushButton_calibsD = QtWidgets.QPushButton(self.tab1)
        self.pushButton_calibsD.setGeometry(QtCore.QRect(28, 16, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_calibsD.setFont(font)
        self.pushButton_calibsD.setObjectName("pushButton_calibsD")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab1)
        self.layoutWidget4.setGeometry(QtCore.QRect(583, 114, 112, 111))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_masterDark_texp = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_masterDark_texp.setText("")
        self.lineEdit_masterDark_texp.setReadOnly(True)
        self.lineEdit_masterDark_texp.setObjectName("lineEdit_masterDark_texp")
        self.verticalLayout_7.addWidget(self.lineEdit_masterDark_texp)
        self.lineEdit_masterFlat_Filter = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_masterFlat_Filter.setText("")
        self.lineEdit_masterFlat_Filter.setReadOnly(True)
        self.lineEdit_masterFlat_Filter.setObjectName("lineEdit_masterFlat_Filter")
        self.verticalLayout_7.addWidget(self.lineEdit_masterFlat_Filter)
        self.comboBox_bpm_action = QtWidgets.QComboBox(self.layoutWidget4)
        self.comboBox_bpm_action.setObjectName("comboBox_bpm_action")
        self.comboBox_bpm_action.addItem("")
        self.comboBox_bpm_action.addItem("")
        self.comboBox_bpm_action.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_bpm_action)
        self.lineEdit_readout_mode = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_readout_mode.setText("")
        self.lineEdit_readout_mode.setReadOnly(True)
        self.lineEdit_readout_mode.setObjectName("lineEdit_readout_mode")
        self.verticalLayout_7.addWidget(self.lineEdit_readout_mode)
        self.tabWidget3.addTab(self.tab1, "")
        self.TabPage1 = QtWidgets.QWidget()
        self.TabPage1.setObjectName("TabPage1")
        self.textLabel1_7 = QtWidgets.QLabel(self.TabPage1)
        self.textLabel1_7.setGeometry(QtCore.QRect(11, 8, 100, 20))
        self.textLabel1_7.setWordWrap(False)
        self.textLabel1_7.setObjectName("textLabel1_7")
        self.textEdit_log_2 = QtWidgets.QTextEdit(self.TabPage1)
        self.textEdit_log_2.setGeometry(QtCore.QRect(10, 30, 901, 391))
        self.textEdit_log_2.setObjectName("textEdit_log_2")
        self.tabWidget3.addTab(self.TabPage1, "")
        self.textEdit_log = QtWidgets.QTextEdit(self.widget)
        self.textEdit_log.setGeometry(QtCore.QRect(5, 480, 941, 181))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.textEdit_log.setPalette(palette)
        self.textEdit_log.setObjectName("textEdit_log")
        panicQL.setCentralWidget(self.widget)
        self.toolBar = QtWidgets.QToolBar(panicQL)
        self.toolBar.setObjectName("toolBar")
        panicQL.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.Toolbar = QtWidgets.QToolBar(panicQL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Toolbar.sizePolicy().hasHeightForWidth())
        self.Toolbar.setSizePolicy(sizePolicy)
        self.Toolbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Toolbar.setAllowedAreas(QtCore.Qt.RightToolBarArea)
        self.Toolbar.setObjectName("Toolbar")
        panicQL.addToolBar(QtCore.Qt.TopToolBarArea, self.Toolbar)
        self.MenuBar = QtWidgets.QMenuBar(panicQL)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 961, 24))
        self.MenuBar.setObjectName("MenuBar")
        self.fileMenu = QtWidgets.QMenu(self.MenuBar)
        self.fileMenu.setObjectName("fileMenu")
        self.viewMenu = QtWidgets.QMenu(self.MenuBar)
        self.viewMenu.setObjectName("viewMenu")
        self.Settings = QtWidgets.QMenu(self.MenuBar)
        self.Settings.setObjectName("Settings")
        self.Calibrations = QtWidgets.QMenu(self.MenuBar)
        self.Calibrations.setObjectName("Calibrations")
        self.Tools = QtWidgets.QMenu(self.MenuBar)
        self.Tools.setObjectName("Tools")
        self.helpMenu = QtWidgets.QMenu(self.MenuBar)
        self.helpMenu.setObjectName("helpMenu")
        panicQL.setMenuBar(self.MenuBar)
        self.fileOpenAction = QtWidgets.QAction(panicQL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/archive-insert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenAction.setIcon(icon1)
        self.fileOpenAction.setProperty("name", "fileOpenAction")
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileDirAction = QtWidgets.QAction(panicQL)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/archive-insert-directory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileDirAction.setIcon(icon2)
        self.fileDirAction.setProperty("name", "fileDirAction")
        self.fileDirAction.setObjectName("fileDirAction")
        self.fileShow = QtWidgets.QAction(panicQL)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/my_icon/images/ds9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/my_icon/images/ds9.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/my_icon/images/ds9.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.fileShow.setIcon(icon3)
        self.fileShow.setProperty("name", "fileShow")
        self.fileShow.setObjectName("fileShow")
        self.fileSaveAsAction = QtWidgets.QAction(panicQL)
        self.fileSaveAsAction.setShortcut("")
        self.fileSaveAsAction.setProperty("name", "fileSaveAsAction")
        self.fileSaveAsAction.setObjectName("fileSaveAsAction")
        self.filePrintAction = QtWidgets.QAction(panicQL)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../.designer/backup/image4"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filePrintAction.setIcon(icon4)
        self.filePrintAction.setProperty("name", "filePrintAction")
        self.filePrintAction.setObjectName("filePrintAction")
        self.fileExitAction = QtWidgets.QAction(panicQL)
        self.fileExitAction.setShortcut("")
        self.fileExitAction.setProperty("name", "fileExitAction")
        self.fileExitAction.setObjectName("fileExitAction")
        self.editCutAction = QtWidgets.QAction(panicQL)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../.designer/backup/image7"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCutAction.setIcon(icon5)
        self.editCutAction.setProperty("name", "editCutAction")
        self.editCutAction.setObjectName("editCutAction")
        self.viewHeaderAction = QtWidgets.QAction(panicQL)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../.designer/backup/image8"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewHeaderAction.setIcon(icon6)
        self.viewHeaderAction.setProperty("name", "editCopyAction")
        self.viewHeaderAction.setObjectName("viewHeaderAction")
        self.viewImageAction = QtWidgets.QAction(panicQL)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../.designer/backup/image9"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewImageAction.setIcon(icon7)
        self.viewImageAction.setProperty("name", "editPasteAction")
        self.viewImageAction.setObjectName("viewImageAction")
        self.editFindAction = QtWidgets.QAction(panicQL)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../.designer/backup/image10"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editFindAction.setIcon(icon8)
        self.editFindAction.setProperty("name", "editFindAction")
        self.editFindAction.setObjectName("editFindAction")
        self.helpIndexAction = QtWidgets.QAction(panicQL)
        self.helpIndexAction.setProperty("name", "helpIndexAction")
        self.helpIndexAction.setObjectName("helpIndexAction")
        self.new_menudAction = QtWidgets.QAction(panicQL)
        self.new_menudAction.setProperty("name", "new_menudAction")
        self.new_menudAction.setObjectName("new_menudAction")
        self.calibrationsMaster_FlatAction = QtWidgets.QAction(panicQL)
        self.calibrationsMaster_FlatAction.setProperty("name", "calibrationsMaster_FlatAction")
        self.calibrationsMaster_FlatAction.setObjectName("calibrationsMaster_FlatAction")
        self.calibrationsMaster_Sky_FlatAction = QtWidgets.QAction(panicQL)
        self.calibrationsMaster_Sky_FlatAction.setProperty("name", "calibrationsMaster_Sky_FlatAction")
        self.calibrationsMaster_Sky_FlatAction.setObjectName("calibrationsMaster_Sky_FlatAction")
        self.toolsIRAF_consoleAction = QtWidgets.QAction(panicQL)
        self.toolsIRAF_consoleAction.setProperty("name", "toolsIRAF_consoleAction")
        self.toolsIRAF_consoleAction.setObjectName("toolsIRAF_consoleAction")
        self.toolsDS9_displayAction = QtWidgets.QAction(panicQL)
        self.toolsDS9_displayAction.setProperty("name", "toolsDS9_displayAction")
        self.toolsDS9_displayAction.setObjectName("toolsDS9_displayAction")
        self.toolsAladinAction = QtWidgets.QAction(panicQL)
        self.toolsAladinAction.setProperty("name", "toolsAladinAction")
        self.toolsAladinAction.setObjectName("toolsAladinAction")
        self.fileSearchAction = QtWidgets.QAction(panicQL)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSearchAction.setIcon(icon9)
        self.fileSearchAction.setProperty("name", "fileSearchAction")
        self.fileSearchAction.setObjectName("fileSearchAction")
        self.quitAction = QtWidgets.QAction(panicQL)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/system-shutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon10)
        self.quitAction.setProperty("name", "quitAction")
        self.quitAction.setObjectName("quitAction")
        self.irafConsoleAction = QtWidgets.QAction(panicQL)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/apps/package_system_shell.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.irafConsoleAction.setIcon(icon11)
        self.irafConsoleAction.setProperty("name", "irafConsoleAction")
        self.irafConsoleAction.setObjectName("irafConsoleAction")
        self.actionAbout = QtWidgets.QAction(panicQL)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAladin = QtWidgets.QAction(panicQL)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/aladin_large.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAladin.setIcon(icon12)
        self.actionAladin.setObjectName("actionAladin")
        self.toolBar.addAction(self.fileOpenAction)
        self.toolBar.addAction(self.fileDirAction)
        self.toolBar.addAction(self.fileShow)
        self.toolBar.addAction(self.fileSearchAction)
        self.toolBar.addAction(self.actionAladin)
        self.toolBar.addAction(self.irafConsoleAction)
        self.Toolbar.addAction(self.quitAction)
        self.fileMenu.addAction(self.fileOpenAction)
        self.fileMenu.addAction(self.fileDirAction)
        self.fileMenu.addAction(self.fileShow)
        self.fileMenu.addAction(self.fileSaveAsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileExitAction)
        self.viewMenu.addAction(self.viewHeaderAction)
        self.viewMenu.addAction(self.viewImageAction)
        self.viewMenu.addSeparator()
        self.viewMenu.addAction(self.editFindAction)
        self.Calibrations.addAction(self.new_menudAction)
        self.Calibrations.addAction(self.calibrationsMaster_FlatAction)
        self.Calibrations.addAction(self.calibrationsMaster_Sky_FlatAction)
        self.Tools.addAction(self.toolsIRAF_consoleAction)
        self.Tools.addAction(self.toolsDS9_displayAction)
        self.Tools.addAction(self.toolsAladinAction)
        self.helpMenu.addAction(self.helpIndexAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.actionAbout)
        self.MenuBar.addAction(self.fileMenu.menuAction())
        self.MenuBar.addAction(self.viewMenu.menuAction())
        self.MenuBar.addAction(self.Settings.menuAction())
        self.MenuBar.addAction(self.Calibrations.menuAction())
        self.MenuBar.addAction(self.Tools.menuAction())
        self.MenuBar.addSeparator()
        self.MenuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(panicQL)
        self.tabWidget3.setCurrentIndex(0)
        self.comboBox_AstromEngine.setCurrentIndex(0)
        self.comboBox_pre_skyWindow.setCurrentIndex(3)
        self.comboBox_detector.setCurrentIndex(0)
        self.viewHeaderAction.activated.connect(panicQL.editCopy)
        self.editCutAction.activated.connect(panicQL.editCut)
        self.editFindAction.activated.connect(panicQL.editFind)
        self.viewImageAction.activated.connect(panicQL.editPaste)
        self.fileDirAction.activated.connect(panicQL.fileOpen)
        self.fileExitAction.activated.connect(panicQL.fileExit)
        self.fileOpenAction.activated.connect(panicQL.add_slot)
        self.filePrintAction.activated.connect(panicQL.filePrint)
        self.fileSaveAsAction.activated.connect(panicQL.fileSaveAs)
        self.fileShow.activated.connect(panicQL.display_slot)
        self.helpIndexAction.activated.connect(panicQL.helpIndex)
        self.irafConsoleAction.activated.connect(panicQL.iraf_console_slot)
        self.quitAction.activated.connect(panicQL.fileExit)
        self.toolsAladinAction.activated.connect(panicQL.start_aladin_slot)
        self.toolsDS9_displayAction.activated.connect(panicQL.start_ds9_slot)
        self.toolsIRAF_consoleAction.activated.connect(panicQL.iraf_console_slot)
        self.helpIndexAction.activated.connect(panicQL.helpIndex)
        self.actionAbout.activated.connect(panicQL.helpAbout)
        self.actionAladin.activated.connect(panicQL.start_aladin_slot)
        self.checkBox_autocheck.clicked.connect(panicQL.autocheck_slot)
        self.checkBox_outDir_autocheck.clicked.connect(panicQL.checkOutDir_slot)
        self.comboBox_classFilter.activated['QString'].connect(panicQL.slot_classFilter)
        self.pushButton_add.clicked.connect(panicQL.add_slot)
        self.pushButton_clear.clicked.connect(panicQL.clear_mainlist_slot)
        self.pushButton_loadLastCalibs.clicked.connect(panicQL.pushB_sel_updateCalibs_slot)
        self.pushButton_master_dark.clicked.connect(panicQL.pushB_sel_masterDark_slot)
        self.pushButton_master_mask.clicked.connect(panicQL.pushB_sel_masterMask_slot)
        self.pushButton_file_filter.clicked.connect(panicQL.filename_filter_slot)
        self.pushButton_dataSourceD.clicked.connect(panicQL.setDataSourceDir_slot)
        self.pushButton_remove.clicked.connect(panicQL.del_slot)
        self.pushButton_outputD.clicked.connect(panicQL.setOutputDir_slot)
        self.pushButton_master_flat.clicked.connect(panicQL.pushB_sel_masterFlat_slot)
        self.pushButton_start_proc.clicked.connect(panicQL.pushB_start_stop_slot)
        self.pushButton_createCalibs.clicked.connect(panicQL.createCalibs_slot)
        self.pushButton_subtract_last2.clicked.connect(panicQL.pushB_subtract_last2_slot)
        self.checkBox_pre_appSF.clicked.connect(self.checkBox_pre_subDark_FF.toggle)
        self.checkBox_pre_subDark_FF.clicked.connect(self.checkBox_pre_appSF.toggle)
        self.pushButton_tempD.clicked.connect(panicQL.setTempDir_slot)
        self.checkBox_geirsFile.clicked.connect(panicQL.setGEIRS_Input_slot)
        self.pushButton_master_nlc.clicked.connect(panicQL.pushB_sel_masterNLC_slot)
        self.checkBox_currentNight.clicked.connect(panicQL.setCurrentNight_Input_slot)
        self.pushButton_calibsD.clicked.connect(panicQL.setCalibsDir_slot)
        QtCore.QMetaObject.connectSlotsByName(panicQL)

    def retranslateUi(self, panicQL):
        _translate = QtCore.QCoreApplication.translate
        panicQL.setWindowTitle(_translate("panicQL", "PANIC QuickLook"))
        self.textLabel1_7_2.setText(_translate("panicQL", "<font color=\"#1759ff\">Event log (Time UTC)</font>"))
        self.checkBox_autocheck.setToolTip(_translate("panicQL", "Autocheck for new incoming images"))
        self.checkBox_outDir_autocheck.setToolTip(_translate("panicQL", "Autocheck for new incoming images to output dir"))
        self.textLabel1_3.setText(_translate("panicQL", "Check"))
        self.pushButton_remove.setToolTip(_translate("panicQL", "Remove data file from the list view, but keeping on disk", "Remove data file from the list view, but keeping on disk"))
        self.pushButton_remove.setText(_translate("panicQL", "Remove"))
        self.pushButton_add.setText(_translate("panicQL", "Add..."))
        self.pushButton_clear.setToolTip(_translate("panicQL", "Clear list view panel, but not files on disk"))
        self.pushButton_clear.setText(_translate("panicQL", "Clear All"))
        self.textLabel2_3.setText(_translate("panicQL", "Last file received:"))
        self.pushButton_dataSourceD.setToolTip(_translate("panicQL", "Select a directory or log file for received files location"))
        self.pushButton_dataSourceD.setText(_translate("panicQL", "Input Dir ..."))
        self.lineEdit_outputD.setToolTip(_translate("panicQL", "Output directory for generated files"))
        self.pushButton_outputD.setToolTip(_translate("panicQL", "Browse the output processed files location"))
        self.pushButton_outputD.setText(_translate("panicQL", "Output Dir ..."))
        self.pushButton_file_filter.setText(_translate("panicQL", "Set Filename Filter"))
        self.pushButton_createCalibs.setText(_translate("panicQL", "Create Calibrations"))
        self.textLabel4_2_3.setText(_translate("panicQL", "Data List View"))
        self.textLabel4_2.setText(_translate("panicQL", "List View Filter"))
        self.comboBox_classFilter.setToolTip(_translate("panicQL", "Filter data sources list using its class/type"))
        self.comboBox_classFilter.setItemText(0, _translate("panicQL", "INPUTS"))
        self.comboBox_classFilter.setItemText(1, _translate("panicQL", "OUTS"))
        self.comboBox_classFilter.setItemText(2, _translate("panicQL", "DARK"))
        self.comboBox_classFilter.setItemText(3, _translate("panicQL", "DOME_FLAT"))
        self.comboBox_classFilter.setItemText(4, _translate("panicQL", "FOCUS"))
        self.comboBox_classFilter.setItemText(5, _translate("panicQL", "SKY_FLAT"))
        self.comboBox_classFilter.setItemText(6, _translate("panicQL", "SCIENCE"))
        self.comboBox_classFilter.setItemText(7, _translate("panicQL", "MASTERS"))
        self.comboBox_classFilter.setItemText(8, _translate("panicQL", "REDUCED"))
        self.comboBox_classFilter.setItemText(9, _translate("panicQL", "GROUP"))
        self.comboBox_classFilter.setItemText(10, _translate("panicQL", "ALL"))
        self.comboBox_QL_Mode.setToolTip(_translate("panicQL", "Filter data sources list using its class/type"))
        self.comboBox_QL_Mode.setItemText(0, _translate("panicQL", "None"))
        self.comboBox_QL_Mode.setItemText(1, _translate("panicQL", "Lazy"))
        self.comboBox_QL_Mode.setItemText(2, _translate("panicQL", "Pre-reduction"))
        self.comboBox_QL_Mode.setItemText(3, _translate("panicQL", "Quick-LEMON"))
        self.comboBox_QL_Mode.setItemText(4, _translate("panicQL", "Full-LEMON"))
        self.comboBox_QL_Mode.setItemText(5, _translate("panicQL", "Full-Reduction"))
        self.textLabel4_2_2.setText(_translate("panicQL", "QL Mode"))
        self.pushButton_start_proc.setText(_translate("panicQL", "START processing"))
        self.pushButton_subtract_last2.setText(_translate("panicQL", "Subtract-Last2"))
        self.lineEdit_sourceD.setToolTip(_translate("panicQL", "Input directory of raw files to read"))
        self.lineEdit_filename_filter.setToolTip(_translate("panicQL", "Input dir files basename filtering (outs are not filtered)"))
        self.lineEdit_filename_filter.setText(_translate("panicQL", "*.fits"))
        self.listView_dataS.setSortingEnabled(True)
        self.listView_dataS.headerItem().setText(0, _translate("panicQL", "Filename"))
        self.listView_dataS.headerItem().setText(1, _translate("panicQL", "ImageType"))
        self.listView_dataS.headerItem().setText(2, _translate("panicQL", "Filter"))
        self.listView_dataS.headerItem().setText(3, _translate("panicQL", "Nimgs"))
        self.listView_dataS.headerItem().setToolTip(3, _translate("panicQL", "Number of images of the cube (=1 if integrated)"))
        self.listView_dataS.headerItem().setText(4, _translate("panicQL", "TExpFile"))
        self.listView_dataS.headerItem().setToolTip(4, _translate("panicQL", "Total integration time of the file (=Nimg*TEXP)"))
        self.listView_dataS.headerItem().setText(5, _translate("panicQL", "DateObs"))
        self.listView_dataS.headerItem().setText(6, _translate("panicQL", "Object"))
        self.listView_dataS.headerItem().setText(7, _translate("panicQL", "RA"))
        self.listView_dataS.headerItem().setText(8, _translate("panicQL", "Dec"))
        self.lineEdit_queue_size.setToolTip(_translate("panicQL", "Number of task currently queued"))
        self.lineEdit_queue_size.setText(_translate("panicQL", "0"))
        self.label.setText(_translate("panicQL", "#Tasks in the queue"))
        self.checkBox_geirsFile.setToolTip(_translate("panicQL", "Auto-select GEIRS log file ~/tmp/fitsGeirsWritten"))
        self.textLabel1_5.setStatusTip(_translate("panicQL", "Read input files from GEIRS log file ~/tmp/fitsGeirsWritten"))
        self.textLabel1_5.setText(_translate("panicQL", "Use GEIRS file"))
        self.checkBox_currentNight.setToolTip(_translate("panicQL", "Auto-select current night directory"))
        self.textLabel1_6.setStatusTip(_translate("panicQL", "Read input files from GEIRS log file ~/tmp/fitsGeirsWritten"))
        self.textLabel1_6.setText(_translate("panicQL", "Current night"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab), _translate("panicQL", "Main"))
        self.groupBox.setTitle(_translate("panicQL", "Common Settings"))
        self.checkBox.setText(_translate("panicQL", "Check header"))
        self.checkBox7_2_2_2.setText(_translate("panicQL", "Create Log file"))
        self.pushButton_tempD.setToolTip(_translate("panicQL", "Browse the temporal file location"))
        self.pushButton_tempD.setText(_translate("panicQL", "Temporary Dir"))
        self.lineEdit_tempD.setToolTip(_translate("panicQL", "Temporal files location"))
        self.lineEdit_tempD.setText(_translate("panicQL", "/tmp/"))
        self.groupBox_2.setTitle(_translate("panicQL", "Data Grouping"))
        self.textLabel5.setText(_translate("panicQL", "arcsecs"))
        self.textLabel5_2.setText(_translate("panicQL", "secs"))
        self.checkBox_data_grouping_OT.setText(_translate("panicQL", "OT Keywords"))
        self.textLabel5_3.setText(_translate("panicQL", "files"))
        self.textLabel4_3.setText(_translate("panicQL", "RA,Dec offsets"))
        self.textLabel4_3_2.setText(_translate("panicQL", "Time offsets"))
        self.textLabel4_3_3.setText(_translate("panicQL", "Max. num.files"))
        self.lineEdit_ra_dec_near_offset.setInputMask(_translate("panicQL", "#####; "))
        self.lineEdit_ra_dec_near_offset.setText(_translate("panicQL", "600"))
        self.lineEdit_time_near_offset.setInputMask(_translate("panicQL", "#####; "))
        self.lineEdit_time_near_offset.setText(_translate("panicQL", "900"))
        self.lineEdit_max_num_files.setInputMask(_translate("panicQL", "####; "))
        self.lineEdit_max_num_files.setText(_translate("panicQL", "50"))
        self.groupBox_3.setTitle(_translate("panicQL", "Astrometry"))
        self.comboBox_AstromCatalog.setItemText(0, _translate("panicQL", "2MASS"))
        self.comboBox_AstromCatalog.setItemText(1, _translate("panicQL", "USNO-B1"))
        self.comboBox_AstromCatalog.setItemText(2, _translate("panicQL", "GSC 2.2"))
        self.comboBox_AstromCatalog.setItemText(3, _translate("panicQL", "SDSS-R5"))
        self.comboBox_AstromCatalog.setItemText(4, _translate("panicQL", "UCAC-2"))
        self.comboBox_AstromCatalog.setItemText(5, _translate("panicQL", "FILE"))
        self.textLabel1_2.setText(_translate("panicQL", "Catalog"))
        self.textLabel3_4.setText(_translate("panicQL", "Astrometric Engine"))
        self.comboBox_AstromEngine.setItemText(0, _translate("panicQL", "AstrometryNet"))
        self.comboBox_AstromEngine.setItemText(1, _translate("panicQL", "SCAMP"))
        self.line_edit_detect_threshold.setInputMask(_translate("panicQL", "##.##; "))
        self.line_edit_detect_threshold.setText(_translate("panicQL", "3.5"))
        self.textLabel4_4.setText(_translate("panicQL", "Detect Threshold"))
        self.groupBox_LazyMode.setTitle(_translate("panicQL", "Lazy Mode"))
        self.checkBox_subDark_FF_BPM.setToolTip(_translate("panicQL", "Substract Dark, apply Flat-Field and grab BPM"))
        self.checkBox_subDark_FF_BPM.setText(_translate("panicQL", "Apply DARK + FLAT + BPM"))
        self.checkBox_subLastFrame.setStatusTip(_translate("panicQL", "Subtract last science frame for sky subtraction"))
        self.checkBox_subLastFrame.setText(_translate("panicQL", "Subtract Last Frame (science)"))
        self.checkBox_subSky.setStatusTip(_translate("panicQL", "Subtract the sky computed from last sky sci frames"))
        self.checkBox_subSky.setText(_translate("panicQL", "Subtract Nearest Sky"))
        self.groupBox_PrereductionMode.setTitle(_translate("panicQL", "Pre-Reduction Mode"))
        self.comboBox_pre_skyWindow.setItemText(0, _translate("panicQL", "1-Current frame"))
        self.comboBox_pre_skyWindow.setItemText(1, _translate("panicQL", "2-frames"))
        self.comboBox_pre_skyWindow.setItemText(2, _translate("panicQL", "3-frames"))
        self.comboBox_pre_skyWindow.setItemText(3, _translate("panicQL", "4-frames"))
        self.comboBox_pre_skyWindow.setItemText(4, _translate("panicQL", "5-frames"))
        self.checkBox_pre_QM.setText(_translate("panicQL", "Quality measurements  (background, psf, ....)"))
        self.textLabel3.setText(_translate("panicQL", "# sky nearest frames"))
        self.checkBox_pre_MA.setText(_translate("panicQL", "Make Astrometry"))
        self.checkBox_pre_appBPM.setText(_translate("panicQL", "Apply BPM"))
        self.checkBox_pre_subDark_FF.setText(_translate("panicQL", "Apply DARK/FLAT"))
        self.checkBox_pre_appSF.setText(_translate("panicQL", "Apply SuperFlat"))
        self.checkBox_pre_BS.setText(_translate("panicQL", "Build stacked image"))
        self.checkBox_pre_appNLC.setText(_translate("panicQL", "Correct for non-linearity"))
        self.comboBox_detector.setItemText(0, _translate("panicQL", "SG1"))
        self.comboBox_detector.setItemText(1, _translate("panicQL", "SG2"))
        self.comboBox_detector.setItemText(2, _translate("panicQL", "SG3"))
        self.comboBox_detector.setItemText(3, _translate("panicQL", "SG4"))
        self.comboBox_detector.setItemText(4, _translate("panicQL", "SG123"))
        self.comboBox_detector.setItemText(5, _translate("panicQL", "All"))
        self.textLabel3_3.setText(_translate("panicQL", "Detector to reduce"))
        self.groupBox_4.setTitle(_translate("panicQL", "Display (ds9)"))
        self.comboBox_show_imgs.setItemText(0, _translate("panicQL", "Only results"))
        self.comboBox_show_imgs.setItemText(1, _translate("panicQL", "Only new files in \'Input Dir\'"))
        self.comboBox_show_imgs.setItemText(2, _translate("panicQL", "All files"))
        self.comboBox_show_imgs.setItemText(3, _translate("panicQL", "None"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.TabPage), _translate("panicQL", "Setup"))
        self.textLabel3_2.setText(_translate("panicQL", "<b>Filter</b>"))
        self.pushButton_loadLastCalibs.setToolTip(_translate("panicQL", "Load last calibration files received"))
        self.pushButton_loadLastCalibs.setWhatsThis(_translate("panicQL", "Load last calibration files received"))
        self.pushButton_loadLastCalibs.setText(_translate("panicQL", "Load last"))
        self.pushButton_test1.setText(_translate("panicQL", "Test1"))
        self.checkBox_use_defCalibs.setToolTip(_translate("panicQL", "Use next files as default calibration files (not recommended!)"))
        self.checkBox_use_defCalibs.setText(_translate("panicQL", "Use as defaults"))
        self.textLabel3_5.setText(_translate("panicQL", "<html><head/><body><p><span style=\" font-weight:600;\">T.Exp.(s)</span></p><p><br/></p></body></html>"))
        self.textLabel3_6.setText(_translate("panicQL", "<html><head/><body><p><span style=\" font-weight:600;\">Readout-Mode</span></p></body></html>"))
        self.pushButton_master_dark.setText(_translate("panicQL", "Master Dark..."))
        self.pushButton_master_flat.setText(_translate("panicQL", "Master Flat..."))
        self.pushButton_master_mask.setText(_translate("panicQL", "Master BPM..."))
        self.pushButton_master_nlc.setText(_translate("panicQL", "Master NLC..."))
        self.textLabel3_7.setText(_translate("panicQL", "<html><head/><body><p>Action</p></body></html>"))
        self.lineEdit_calibsD.setToolTip(_translate("panicQL", "Directory of master calibrations files (masterDark, masterFlats, ...)"))
        self.pushButton_calibsD.setToolTip(_translate("panicQL", "Select a directory or log file for received files location"))
        self.pushButton_calibsD.setText(_translate("panicQL", "Set Calibs Dir..."))
        self.comboBox_bpm_action.setItemText(0, _translate("panicQL", "None"))
        self.comboBox_bpm_action.setItemText(1, _translate("panicQL", "Set NaNs"))
        self.comboBox_bpm_action.setItemText(2, _translate("panicQL", "Fix"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab1), _translate("panicQL", "Calibrations"))
        self.textLabel1_7.setText(_translate("panicQL", "<font color=\"#1759ff\">Times in UTC</font>"))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.TabPage1), _translate("panicQL", "Logs"))
        self.toolBar.setProperty("label", _translate("panicQL", "Tools"))
        self.Toolbar.setProperty("label", _translate("panicQL", "Toolbar"))
        self.fileMenu.setTitle(_translate("panicQL", "&File"))
        self.viewMenu.setTitle(_translate("panicQL", "View"))
        self.Settings.setTitle(_translate("panicQL", "Settings"))
        self.Calibrations.setTitle(_translate("panicQL", "Calibrations"))
        self.Tools.setTitle(_translate("panicQL", "Tools"))
        self.helpMenu.setTitle(_translate("panicQL", "&Help"))
        self.fileOpenAction.setText(_translate("panicQL", "&Open"))
        self.fileOpenAction.setIconText(_translate("panicQL", "Open"))
        self.fileOpenAction.setToolTip(_translate("panicQL", "Add a new file to \'Data List View\'"))
        self.fileOpenAction.setShortcut(_translate("panicQL", "Ctrl+O"))
        self.fileDirAction.setText(_translate("panicQL", "&Open..."))
        self.fileDirAction.setIconText(_translate("panicQL", "Open"))
        self.fileDirAction.setToolTip(_translate("panicQL", "Change data source directory"))
        self.fileDirAction.setShortcut(_translate("panicQL", "Ctrl+I"))
        self.fileShow.setText(_translate("panicQL", "&Show"))
        self.fileShow.setIconText(_translate("panicQL", "Show"))
        self.fileShow.setToolTip(_translate("panicQL", "Show image"))
        self.fileShow.setShortcut(_translate("panicQL", "Ctrl+D"))
        self.fileSaveAsAction.setText(_translate("panicQL", "Save &As..."))
        self.fileSaveAsAction.setIconText(_translate("panicQL", "Save As"))
        self.filePrintAction.setText(_translate("panicQL", "&Print..."))
        self.filePrintAction.setIconText(_translate("panicQL", "Print"))
        self.fileExitAction.setText(_translate("panicQL", "E&xit"))
        self.fileExitAction.setIconText(_translate("panicQL", "Exit"))
        self.editCutAction.setText(_translate("panicQL", "Cu&t"))
        self.editCutAction.setIconText(_translate("panicQL", "Cut"))
        self.viewHeaderAction.setText(_translate("panicQL", "&Header"))
        self.viewHeaderAction.setIconText(_translate("panicQL", "Copy"))
        self.viewImageAction.setText(_translate("panicQL", "&Paste"))
        self.viewImageAction.setIconText(_translate("panicQL", "Paste"))
        self.editFindAction.setText(_translate("panicQL", "&Find..."))
        self.editFindAction.setIconText(_translate("panicQL", "Find"))
        self.helpIndexAction.setText(_translate("panicQL", "&Index..."))
        self.helpIndexAction.setIconText(_translate("panicQL", "Index"))
        self.helpIndexAction.setShortcut(_translate("panicQL", "F1"))
        self.new_menudAction.setText(_translate("panicQL", "Master Dark"))
        self.new_menudAction.setIconText(_translate("panicQL", "Master Dark"))
        self.calibrationsMaster_FlatAction.setText(_translate("panicQL", "Master Dome-Flat"))
        self.calibrationsMaster_FlatAction.setIconText(_translate("panicQL", "Master Dome-Flat"))
        self.calibrationsMaster_Sky_FlatAction.setText(_translate("panicQL", "Master Sky-Flat"))
        self.calibrationsMaster_Sky_FlatAction.setIconText(_translate("panicQL", "Master Sky-Flat"))
        self.toolsIRAF_consoleAction.setText(_translate("panicQL", "IRAF console"))
        self.toolsIRAF_consoleAction.setIconText(_translate("panicQL", "IRAF console"))
        self.toolsIRAF_consoleAction.setShortcut(_translate("panicQL", "Shift+I"))
        self.toolsDS9_displayAction.setText(_translate("panicQL", "DS9 display"))
        self.toolsDS9_displayAction.setIconText(_translate("panicQL", "DS9 display"))
        self.toolsDS9_displayAction.setShortcut(_translate("panicQL", "Ctrl+D"))
        self.toolsAladinAction.setText(_translate("panicQL", "Aladin"))
        self.toolsAladinAction.setIconText(_translate("panicQL", "Aladin"))
        self.toolsAladinAction.setShortcut(_translate("panicQL", "Ctrl+A"))
        self.fileSearchAction.setIconText(_translate("panicQL", "Action"))
        self.fileSearchAction.setToolTip(_translate("panicQL", "Search files"))
        self.quitAction.setIconText(_translate("panicQL", "Action"))
        self.quitAction.setToolTip(_translate("panicQL", "Quit Quick-Look"))
        self.irafConsoleAction.setIconText(_translate("panicQL", "Action"))
        self.irafConsoleAction.setToolTip(_translate("panicQL", "Open an IRAF console"))
        self.irafConsoleAction.setShortcut(_translate("panicQL", "Shift+I"))
        self.actionAbout.setText(_translate("panicQL", "About"))
        self.actionAladin.setText(_translate("panicQL", "Aladin"))
        self.actionAladin.setToolTip(_translate("panicQL", "Open Aladin application"))
        self.actionAladin.setShortcut(_translate("panicQL", "Ctrl+A"))

import panicQL_resources_rc
