# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panicQL.ui'
#
# Created by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_panicQL(object):
    def setupUi(self, panicQL):
        panicQL.setObjectName(_fromUtf8("panicQL"))
        panicQL.resize(961, 729)
        self.widget = QtGui.QWidget(panicQL)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.textLabel1_7_2 = QtGui.QLabel(self.widget)
        self.textLabel1_7_2.setGeometry(QtCore.QRect(14, 458, 220, 22))
        self.textLabel1_7_2.setWordWrap(False)
        self.textLabel1_7_2.setObjectName(_fromUtf8("textLabel1_7_2"))
        self.tabWidget3 = QtGui.QTabWidget(self.widget)
        self.tabWidget3.setGeometry(QtCore.QRect(0, 0, 940, 460))
        self.tabWidget3.setObjectName(_fromUtf8("tabWidget3"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.checkBox_autocheck = QtGui.QCheckBox(self.tab)
        self.checkBox_autocheck.setGeometry(QtCore.QRect(440, 31, 20, 20))
        self.checkBox_autocheck.setText(_fromUtf8(""))
        self.checkBox_autocheck.setChecked(False)
        self.checkBox_autocheck.setObjectName(_fromUtf8("checkBox_autocheck"))
        self.checkBox_outDir_autocheck = QtGui.QCheckBox(self.tab)
        self.checkBox_outDir_autocheck.setGeometry(QtCore.QRect(441, 64, 20, 20))
        self.checkBox_outDir_autocheck.setText(_fromUtf8(""))
        self.checkBox_outDir_autocheck.setObjectName(_fromUtf8("checkBox_outDir_autocheck"))
        self.textLabel1_3 = QtGui.QLabel(self.tab)
        self.textLabel1_3.setGeometry(QtCore.QRect(430, 10, 50, 20))
        self.textLabel1_3.setWordWrap(False)
        self.textLabel1_3.setObjectName(_fromUtf8("textLabel1_3"))
        self.pushButton_remove = QtGui.QPushButton(self.tab)
        self.pushButton_remove.setGeometry(QtCore.QRect(755, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setObjectName(_fromUtf8("pushButton_remove"))
        self.pushButton_add = QtGui.QPushButton(self.tab)
        self.pushButton_add.setGeometry(QtCore.QRect(671, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.pixmapLabel1_2 = QtGui.QLabel(self.tab)
        self.pixmapLabel1_2.setGeometry(QtCore.QRect(767, 5, 141, 100))
        self.pixmapLabel1_2.setPixmap(QtGui.QPixmap(_fromUtf8("images/logo_PANIC.jpg")))
        self.pixmapLabel1_2.setScaledContents(True)
        self.pixmapLabel1_2.setWordWrap(False)
        self.pixmapLabel1_2.setObjectName(_fromUtf8("pixmapLabel1_2"))
        self.pushButton_clear = QtGui.QPushButton(self.tab)
        self.pushButton_clear.setGeometry(QtCore.QRect(843, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.textLabel2_3 = QtGui.QLabel(self.tab)
        self.textLabel2_3.setGeometry(QtCore.QRect(10, 390, 102, 20))
        self.textLabel2_3.setWordWrap(False)
        self.textLabel2_3.setObjectName(_fromUtf8("textLabel2_3"))
        self.lineEdit_last_file = QtGui.QLineEdit(self.tab)
        self.lineEdit_last_file.setGeometry(QtCore.QRect(120, 390, 311, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_last_file.setPalette(palette)
        self.lineEdit_last_file.setReadOnly(True)
        self.lineEdit_last_file.setObjectName(_fromUtf8("lineEdit_last_file"))
        self.pushButton_dataSourceD = QtGui.QPushButton(self.tab)
        self.pushButton_dataSourceD.setGeometry(QtCore.QRect(19, 27, 110, 23))
        self.pushButton_dataSourceD.setObjectName(_fromUtf8("pushButton_dataSourceD"))
        self.lineEdit_outputD = QtGui.QLineEdit(self.tab)
        self.lineEdit_outputD.setGeometry(QtCore.QRect(141, 63, 290, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_outputD.setPalette(palette)
        self.lineEdit_outputD.setReadOnly(True)
        self.lineEdit_outputD.setObjectName(_fromUtf8("lineEdit_outputD"))
        self.pushButton_outputD = QtGui.QPushButton(self.tab)
        self.pushButton_outputD.setGeometry(QtCore.QRect(19, 61, 110, 23))
        self.pushButton_outputD.setObjectName(_fromUtf8("pushButton_outputD"))
        self.pushButton_file_filter = QtGui.QPushButton(self.tab)
        self.pushButton_file_filter.setGeometry(QtCore.QRect(558, 30, 131, 23))
        self.pushButton_file_filter.setObjectName(_fromUtf8("pushButton_file_filter"))
        self.pushButton_createCalibs = QtGui.QPushButton(self.tab)
        self.pushButton_createCalibs.setGeometry(QtCore.QRect(770, 110, 140, 23))
        self.pushButton_createCalibs.setObjectName(_fromUtf8("pushButton_createCalibs"))
        self.textLabel4_2_3 = QtGui.QLabel(self.tab)
        self.textLabel4_2_3.setGeometry(QtCore.QRect(20, 150, 110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2_3.setFont(font)
        self.textLabel4_2_3.setWordWrap(False)
        self.textLabel4_2_3.setObjectName(_fromUtf8("textLabel4_2_3"))
        self.textLabel4_2 = QtGui.QLabel(self.tab)
        self.textLabel4_2.setGeometry(QtCore.QRect(18, 101, 110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2.setFont(font)
        self.textLabel4_2.setWordWrap(False)
        self.textLabel4_2.setObjectName(_fromUtf8("textLabel4_2"))
        self.comboBox_classFilter = QtGui.QComboBox(self.tab)
        self.comboBox_classFilter.setGeometry(QtCore.QRect(18, 121, 110, 21))
        self.comboBox_classFilter.setObjectName(_fromUtf8("comboBox_classFilter"))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode = QtGui.QComboBox(self.tab)
        self.comboBox_QL_Mode.setGeometry(QtCore.QRect(154, 121, 110, 21))
        self.comboBox_QL_Mode.setObjectName(_fromUtf8("comboBox_QL_Mode"))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.textLabel4_2_2 = QtGui.QLabel(self.tab)
        self.textLabel4_2_2.setGeometry(QtCore.QRect(160, 100, 80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2_2.setFont(font)
        self.textLabel4_2_2.setWordWrap(False)
        self.textLabel4_2_2.setObjectName(_fromUtf8("textLabel4_2_2"))
        self.pushButton_start_proc = QtGui.QPushButton(self.tab)
        self.pushButton_start_proc.setGeometry(QtCore.QRect(770, 140, 140, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_start_proc.setPalette(palette)
        self.pushButton_start_proc.setObjectName(_fromUtf8("pushButton_start_proc"))
        self.pushButton_subtract_last2 = QtGui.QPushButton(self.tab)
        self.pushButton_subtract_last2.setGeometry(QtCore.QRect(650, 139, 111, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_subtract_last2.setPalette(palette)
        self.pushButton_subtract_last2.setObjectName(_fromUtf8("pushButton_subtract_last2"))
        self.lineEdit_sourceD = QtGui.QLineEdit(self.tab)
        self.lineEdit_sourceD.setGeometry(QtCore.QRect(140, 30, 290, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_sourceD.setPalette(palette)
        self.lineEdit_sourceD.setReadOnly(True)
        self.lineEdit_sourceD.setObjectName(_fromUtf8("lineEdit_sourceD"))
        self.lineEdit_filename_filter = QtGui.QLineEdit(self.tab)
        self.lineEdit_filename_filter.setGeometry(QtCore.QRect(492, 30, 60, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_filename_filter.setPalette(palette)
        self.lineEdit_filename_filter.setAlignment(QtCore.Qt.AlignRight)
        self.lineEdit_filename_filter.setReadOnly(True)
        self.lineEdit_filename_filter.setObjectName(_fromUtf8("lineEdit_filename_filter"))
        self.listView_dataS = QtGui.QTreeWidget(self.tab)
        self.listView_dataS.setGeometry(QtCore.QRect(10, 170, 911, 211))
        self.listView_dataS.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView_dataS.setObjectName(_fromUtf8("listView_dataS"))
        self.listView_dataS.header().setStretchLastSection(True)
        self.lineEdit_queue_size = QtGui.QLineEdit(self.tab)
        self.lineEdit_queue_size.setGeometry(QtCore.QRect(494, 64, 60, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_queue_size.setPalette(palette)
        self.lineEdit_queue_size.setAlignment(QtCore.Qt.AlignRight)
        self.lineEdit_queue_size.setReadOnly(True)
        self.lineEdit_queue_size.setObjectName(_fromUtf8("lineEdit_queue_size"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(563, 65, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget3.addTab(self.tab, _fromUtf8(""))
        self.TabPage = QtGui.QWidget()
        self.TabPage.setObjectName(_fromUtf8("TabPage"))
        self.groupBox = QtGui.QGroupBox(self.TabPage)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 181, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox7_2_2_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox7_2_2_2.setChecked(True)
        self.checkBox7_2_2_2.setObjectName(_fromUtf8("checkBox7_2_2_2"))
        self.verticalLayout_2.addWidget(self.checkBox7_2_2_2)
        self.pushButton_tempD = QtGui.QPushButton(self.groupBox)
        self.pushButton_tempD.setObjectName(_fromUtf8("pushButton_tempD"))
        self.verticalLayout_2.addWidget(self.pushButton_tempD)
        self.lineEdit_tempD = QtGui.QLineEdit(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_tempD.setPalette(palette)
        self.lineEdit_tempD.setReadOnly(True)
        self.lineEdit_tempD.setObjectName(_fromUtf8("lineEdit_tempD"))
        self.verticalLayout_2.addWidget(self.lineEdit_tempD)
        self.groupBox_2 = QtGui.QGroupBox(self.TabPage)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 10, 421, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.textLabel5 = QtGui.QLabel(self.groupBox_2)
        self.textLabel5.setGeometry(QtCore.QRect(192, 22, 58, 20))
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName(_fromUtf8("textLabel5"))
        self.textLabel5_2 = QtGui.QLabel(self.groupBox_2)
        self.textLabel5_2.setGeometry(QtCore.QRect(192, 45, 58, 20))
        self.textLabel5_2.setMidLineWidth(1)
        self.textLabel5_2.setWordWrap(False)
        self.textLabel5_2.setObjectName(_fromUtf8("textLabel5_2"))
        self.checkBox_data_grouping_OT = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_data_grouping_OT.setGeometry(QtCore.QRect(260, 70, 140, 19))
        self.checkBox_data_grouping_OT.setChecked(False)
        self.checkBox_data_grouping_OT.setObjectName(_fromUtf8("checkBox_data_grouping_OT"))
        self.textLabel5_3 = QtGui.QLabel(self.groupBox_2)
        self.textLabel5_3.setGeometry(QtCore.QRect(192, 70, 58, 20))
        self.textLabel5_3.setMidLineWidth(1)
        self.textLabel5_3.setWordWrap(False)
        self.textLabel5_3.setObjectName(_fromUtf8("textLabel5_3"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 91, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textLabel4_3 = QtGui.QLabel(self.layoutWidget)
        self.textLabel4_3.setWordWrap(False)
        self.textLabel4_3.setObjectName(_fromUtf8("textLabel4_3"))
        self.verticalLayout_3.addWidget(self.textLabel4_3)
        self.textLabel4_3_2 = QtGui.QLabel(self.layoutWidget)
        self.textLabel4_3_2.setWordWrap(False)
        self.textLabel4_3_2.setObjectName(_fromUtf8("textLabel4_3_2"))
        self.verticalLayout_3.addWidget(self.textLabel4_3_2)
        self.textLabel4_3_3 = QtGui.QLabel(self.layoutWidget)
        self.textLabel4_3_3.setWordWrap(False)
        self.textLabel4_3_3.setObjectName(_fromUtf8("textLabel4_3_3"))
        self.verticalLayout_3.addWidget(self.textLabel4_3_3)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 20, 61, 76))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit_ra_dec_near_offset = QtGui.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_ra_dec_near_offset.setPalette(palette)
        self.lineEdit_ra_dec_near_offset.setObjectName(_fromUtf8("lineEdit_ra_dec_near_offset"))
        self.verticalLayout_4.addWidget(self.lineEdit_ra_dec_near_offset)
        self.lineEdit_time_near_offset = QtGui.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_time_near_offset.setPalette(palette)
        self.lineEdit_time_near_offset.setObjectName(_fromUtf8("lineEdit_time_near_offset"))
        self.verticalLayout_4.addWidget(self.lineEdit_time_near_offset)
        self.lineEdit_max_num_files = QtGui.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_max_num_files.setPalette(palette)
        self.lineEdit_max_num_files.setObjectName(_fromUtf8("lineEdit_max_num_files"))
        self.verticalLayout_4.addWidget(self.lineEdit_max_num_files)
        self.groupBox_3 = QtGui.QGroupBox(self.TabPage)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 10, 251, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_AstromCatalog = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_AstromCatalog.setGeometry(QtCore.QRect(20, 40, 90, 21))
        self.comboBox_AstromCatalog.setObjectName(_fromUtf8("comboBox_AstromCatalog"))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.checkBox_doRegrig = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_doRegrig.setGeometry(QtCore.QRect(28, 70, 140, 19))
        self.checkBox_doRegrig.setObjectName(_fromUtf8("checkBox_doRegrig"))
        self.textLabel1_2 = QtGui.QLabel(self.groupBox_3)
        self.textLabel1_2.setGeometry(QtCore.QRect(20, 20, 58, 20))
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName(_fromUtf8("textLabel1_2"))
        self.groupBox_LazyMode = QtGui.QGroupBox(self.TabPage)
        self.groupBox_LazyMode.setGeometry(QtCore.QRect(20, 153, 271, 260))
        self.groupBox_LazyMode.setObjectName(_fromUtf8("groupBox_LazyMode"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_LazyMode)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox_show_imgs = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_show_imgs.setChecked(True)
        self.checkBox_show_imgs.setObjectName(_fromUtf8("checkBox_show_imgs"))
        self.verticalLayout.addWidget(self.checkBox_show_imgs)
        self.checkBox_subDark = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subDark.setChecked(False)
        self.checkBox_subDark.setObjectName(_fromUtf8("checkBox_subDark"))
        self.verticalLayout.addWidget(self.checkBox_subDark)
        self.checkBox_appBPM = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_appBPM.setEnabled(False)
        self.checkBox_appBPM.setObjectName(_fromUtf8("checkBox_appBPM"))
        self.verticalLayout.addWidget(self.checkBox_appBPM)
        self.checkBox_appFlat = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_appFlat.setChecked(False)
        self.checkBox_appFlat.setObjectName(_fromUtf8("checkBox_appFlat"))
        self.verticalLayout.addWidget(self.checkBox_appFlat)
        self.checkBox_subLastFrame = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subLastFrame.setObjectName(_fromUtf8("checkBox_subLastFrame"))
        self.verticalLayout.addWidget(self.checkBox_subLastFrame)
        self.checkBox_subSky = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subSky.setEnabled(True)
        self.checkBox_subSky.setObjectName(_fromUtf8("checkBox_subSky"))
        self.verticalLayout.addWidget(self.checkBox_subSky)
        self.checkBox_appSAstrom = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_appSAstrom.setEnabled(False)
        self.checkBox_appSAstrom.setObjectName(_fromUtf8("checkBox_appSAstrom"))
        self.verticalLayout.addWidget(self.checkBox_appSAstrom)
        self.groupBox_PrereductionMode = QtGui.QGroupBox(self.TabPage)
        self.groupBox_PrereductionMode.setGeometry(QtCore.QRect(310, 152, 601, 271))
        self.groupBox_PrereductionMode.setObjectName(_fromUtf8("groupBox_PrereductionMode"))
        self.comboBox_pre_skyWindow = QtGui.QComboBox(self.groupBox_PrereductionMode)
        self.comboBox_pre_skyWindow.setGeometry(QtCore.QRect(27, 170, 118, 21))
        self.comboBox_pre_skyWindow.setObjectName(_fromUtf8("comboBox_pre_skyWindow"))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.checkBox_pre_QM = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_QM.setGeometry(QtCore.QRect(196, 89, 291, 19))
        self.checkBox_pre_QM.setObjectName(_fromUtf8("checkBox_pre_QM"))
        self.textLabel3 = QtGui.QLabel(self.groupBox_PrereductionMode)
        self.textLabel3.setGeometry(QtCore.QRect(27, 150, 130, 16))
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName(_fromUtf8("textLabel3"))
        self.checkBox_pre_MA = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_MA.setGeometry(QtCore.QRect(196, 39, 180, 19))
        self.checkBox_pre_MA.setChecked(True)
        self.checkBox_pre_MA.setObjectName(_fromUtf8("checkBox_pre_MA"))
        self.checkBox_pre_compDM = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_compDM.setGeometry(QtCore.QRect(196, 63, 180, 19))
        self.checkBox_pre_compDM.setChecked(True)
        self.checkBox_pre_compDM.setObjectName(_fromUtf8("checkBox_pre_compDM"))
        self.checkBox_pre_subD = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_subD.setGeometry(QtCore.QRect(30, 39, 140, 19))
        self.checkBox_pre_subD.setChecked(False)
        self.checkBox_pre_subD.setObjectName(_fromUtf8("checkBox_pre_subD"))
        self.checkBox_pre_appMF = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appMF.setGeometry(QtCore.QRect(30, 65, 180, 19))
        self.checkBox_pre_appMF.setChecked(False)
        self.checkBox_pre_appMF.setObjectName(_fromUtf8("checkBox_pre_appMF"))
        self.checkBox_pre_appSF = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appSF.setGeometry(QtCore.QRect(30, 90, 180, 19))
        self.checkBox_pre_appSF.setChecked(True)
        self.checkBox_pre_appSF.setObjectName(_fromUtf8("checkBox_pre_appSF"))
        self.checkBox_pre_BS = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_BS.setGeometry(QtCore.QRect(198, 120, 140, 19))
        self.checkBox_pre_BS.setChecked(True)
        self.checkBox_pre_BS.setObjectName(_fromUtf8("checkBox_pre_BS"))
        self.tabWidget3.addTab(self.TabPage, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.pushButton_Darks_add = QtGui.QPushButton(self.tab1)
        self.pushButton_Darks_add.setGeometry(QtCore.QRect(19, 40, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Darks_add.setFont(font)
        self.pushButton_Darks_add.setObjectName(_fromUtf8("pushButton_Darks_add"))
        self.pushButton_DomeF_add = QtGui.QPushButton(self.tab1)
        self.pushButton_DomeF_add.setGeometry(QtCore.QRect(180, 40, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_DomeF_add.setFont(font)
        self.pushButton_DomeF_add.setObjectName(_fromUtf8("pushButton_DomeF_add"))
        self.pushButton_SkyF_add = QtGui.QPushButton(self.tab1)
        self.pushButton_SkyF_add.setGeometry(QtCore.QRect(360, 40, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SkyF_add.setFont(font)
        self.pushButton_SkyF_add.setObjectName(_fromUtf8("pushButton_SkyF_add"))
        self.pushButton_Darks_del = QtGui.QPushButton(self.tab1)
        self.pushButton_Darks_del.setGeometry(QtCore.QRect(88, 40, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Darks_del.setFont(font)
        self.pushButton_Darks_del.setObjectName(_fromUtf8("pushButton_Darks_del"))
        self.pushButton_DFlat_del = QtGui.QPushButton(self.tab1)
        self.pushButton_DFlat_del.setGeometry(QtCore.QRect(254, 41, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_DFlat_del.setFont(font)
        self.pushButton_DFlat_del.setObjectName(_fromUtf8("pushButton_DFlat_del"))
        self.pushButton_SFlat_del = QtGui.QPushButton(self.tab1)
        self.pushButton_SFlat_del.setGeometry(QtCore.QRect(430, 40, 50, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_SFlat_del.setFont(font)
        self.pushButton_SFlat_del.setObjectName(_fromUtf8("pushButton_SFlat_del"))
        self.textLabel3_2 = QtGui.QLabel(self.tab1)
        self.textLabel3_2.setGeometry(QtCore.QRect(510, 340, 51, 22))
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName(_fromUtf8("textLabel3_2"))
        self.lineEdit_masterFlat_Filter = QtGui.QLineEdit(self.tab1)
        self.lineEdit_masterFlat_Filter.setGeometry(QtCore.QRect(557, 340, 70, 21))
        self.lineEdit_masterFlat_Filter.setText(_fromUtf8(""))
        self.lineEdit_masterFlat_Filter.setReadOnly(True)
        self.lineEdit_masterFlat_Filter.setObjectName(_fromUtf8("lineEdit_masterFlat_Filter"))
        self.pushButton_master_mask = QtGui.QPushButton(self.tab1)
        self.pushButton_master_mask.setGeometry(QtCore.QRect(12, 368, 120, 23))
        self.pushButton_master_mask.setObjectName(_fromUtf8("pushButton_master_mask"))
        self.lineEdit_masterMask = QtGui.QLineEdit(self.tab1)
        self.lineEdit_masterMask.setGeometry(QtCore.QRect(138, 370, 360, 21))
        self.lineEdit_masterMask.setReadOnly(True)
        self.lineEdit_masterMask.setObjectName(_fromUtf8("lineEdit_masterMask"))
        self.lineEdit_masterFlat = QtGui.QLineEdit(self.tab1)
        self.lineEdit_masterFlat.setGeometry(QtCore.QRect(139, 340, 360, 21))
        self.lineEdit_masterFlat.setReadOnly(True)
        self.lineEdit_masterFlat.setObjectName(_fromUtf8("lineEdit_masterFlat"))
        self.lineEdit_masterDark = QtGui.QLineEdit(self.tab1)
        self.lineEdit_masterDark.setGeometry(QtCore.QRect(141, 311, 360, 21))
        self.lineEdit_masterDark.setReadOnly(True)
        self.lineEdit_masterDark.setObjectName(_fromUtf8("lineEdit_masterDark"))
        self.pushButton_master_flat = QtGui.QPushButton(self.tab1)
        self.pushButton_master_flat.setGeometry(QtCore.QRect(11, 338, 120, 23))
        self.pushButton_master_flat.setObjectName(_fromUtf8("pushButton_master_flat"))
        self.pushButton_master_dark = QtGui.QPushButton(self.tab1)
        self.pushButton_master_dark.setGeometry(QtCore.QRect(12, 309, 120, 23))
        self.pushButton_master_dark.setObjectName(_fromUtf8("pushButton_master_dark"))
        self.pushButton_createMDark = QtGui.QPushButton(self.tab1)
        self.pushButton_createMDark.setGeometry(QtCore.QRect(16, 266, 120, 20))
        self.pushButton_createMDark.setObjectName(_fromUtf8("pushButton_createMDark"))
        self.textLabel1_4 = QtGui.QLabel(self.tab1)
        self.textLabel1_4.setGeometry(QtCore.QRect(55, 15, 48, 22))
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName(_fromUtf8("textLabel1_4"))
        self.pushButton_createMDF = QtGui.QPushButton(self.tab1)
        self.pushButton_createMDF.setGeometry(QtCore.QRect(190, 270, 120, 20))
        self.pushButton_createMDF.setObjectName(_fromUtf8("pushButton_createMDF"))
        self.pushButton_createMSF = QtGui.QPushButton(self.tab1)
        self.pushButton_createMSF.setGeometry(QtCore.QRect(359, 269, 130, 20))
        self.pushButton_createMSF.setObjectName(_fromUtf8("pushButton_createMSF"))
        self.textLabel1_4_2 = QtGui.QLabel(self.tab1)
        self.textLabel1_4_2.setGeometry(QtCore.QRect(209, 17, 110, 22))
        self.textLabel1_4_2.setWordWrap(False)
        self.textLabel1_4_2.setObjectName(_fromUtf8("textLabel1_4_2"))
        self.textLabel1_4_2_2 = QtGui.QLabel(self.tab1)
        self.textLabel1_4_2_2.setGeometry(QtCore.QRect(383, 16, 80, 22))
        self.textLabel1_4_2_2.setWordWrap(False)
        self.textLabel1_4_2_2.setObjectName(_fromUtf8("textLabel1_4_2_2"))
        self.pushButton_test1 = QtGui.QPushButton(self.tab1)
        self.pushButton_test1.setGeometry(QtCore.QRect(800, 40, 108, 23))
        self.pushButton_test1.setObjectName(_fromUtf8("pushButton_test1"))
        self.listBox_SkyF = QtGui.QListWidget(self.tab1)
        self.listBox_SkyF.setGeometry(QtCore.QRect(350, 80, 151, 181))
        self.listBox_SkyF.setObjectName(_fromUtf8("listBox_SkyF"))
        self.listBox_domeF = QtGui.QListWidget(self.tab1)
        self.listBox_domeF.setGeometry(QtCore.QRect(170, 80, 151, 181))
        self.listBox_domeF.setObjectName(_fromUtf8("listBox_domeF"))
        self.listBox_darks = QtGui.QListWidget(self.tab1)
        self.listBox_darks.setGeometry(QtCore.QRect(10, 80, 131, 181))
        self.listBox_darks.setObjectName(_fromUtf8("listBox_darks"))
        self.tabWidget3.addTab(self.tab1, _fromUtf8(""))
        self.TabPage1 = QtGui.QWidget()
        self.TabPage1.setObjectName(_fromUtf8("TabPage1"))
        self.textLabel1_7 = QtGui.QLabel(self.TabPage1)
        self.textLabel1_7.setGeometry(QtCore.QRect(11, 8, 100, 20))
        self.textLabel1_7.setWordWrap(False)
        self.textLabel1_7.setObjectName(_fromUtf8("textLabel1_7"))
        self.textEdit_log_2 = QtGui.QTextEdit(self.TabPage1)
        self.textEdit_log_2.setGeometry(QtCore.QRect(10, 30, 901, 391))
        self.textEdit_log_2.setObjectName(_fromUtf8("textEdit_log_2"))
        self.tabWidget3.addTab(self.TabPage1, _fromUtf8(""))
        self.textEdit_log = QtGui.QTextEdit(self.widget)
        self.textEdit_log.setGeometry(QtCore.QRect(5, 480, 941, 181))
        self.textEdit_log.setObjectName(_fromUtf8("textEdit_log"))
        panicQL.setCentralWidget(self.widget)
        self.toolBar = QtGui.QToolBar(panicQL)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        panicQL.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.Toolbar = QtGui.QToolBar(panicQL)
        self.Toolbar.setObjectName(_fromUtf8("Toolbar"))
        panicQL.addToolBar(QtCore.Qt.TopToolBarArea, self.Toolbar)
        self.MenuBar = QtGui.QMenuBar(panicQL)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 961, 20))
        self.MenuBar.setObjectName(_fromUtf8("MenuBar"))
        self.fileMenu = QtGui.QMenu(self.MenuBar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.editMenu = QtGui.QMenu(self.MenuBar)
        self.editMenu.setObjectName(_fromUtf8("editMenu"))
        self.Settings = QtGui.QMenu(self.MenuBar)
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.Calibrations = QtGui.QMenu(self.MenuBar)
        self.Calibrations.setObjectName(_fromUtf8("Calibrations"))
        self.Tools = QtGui.QMenu(self.MenuBar)
        self.Tools.setObjectName(_fromUtf8("Tools"))
        self.helpMenu = QtGui.QMenu(self.MenuBar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        panicQL.setMenuBar(self.MenuBar)
        self.fileOpenAction = QtGui.QAction(panicQL)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/archive-insert.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenAction.setIcon(icon)
        self.fileOpenAction.setProperty("name", _fromUtf8("fileOpenAction"))
        self.fileOpenAction.setObjectName(_fromUtf8("fileOpenAction"))
        self.fileDirAction = QtGui.QAction(panicQL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/archive-insert-directory.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileDirAction.setIcon(icon1)
        self.fileDirAction.setProperty("name", _fromUtf8("fileDirAction"))
        self.fileDirAction.setObjectName(_fromUtf8("fileDirAction"))
        self.fileShow = QtGui.QAction(panicQL)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../usr/share/icons/hicolor/16x16/apps/eyes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileShow.setIcon(icon2)
        self.fileShow.setProperty("name", _fromUtf8("fileShow"))
        self.fileShow.setObjectName(_fromUtf8("fileShow"))
        self.fileSaveAsAction = QtGui.QAction(panicQL)
        self.fileSaveAsAction.setShortcut(_fromUtf8(""))
        self.fileSaveAsAction.setProperty("name", _fromUtf8("fileSaveAsAction"))
        self.fileSaveAsAction.setObjectName(_fromUtf8("fileSaveAsAction"))
        self.filePrintAction = QtGui.QAction(panicQL)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../.designer/backup/image4")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filePrintAction.setIcon(icon3)
        self.filePrintAction.setProperty("name", _fromUtf8("filePrintAction"))
        self.filePrintAction.setObjectName(_fromUtf8("filePrintAction"))
        self.fileExitAction = QtGui.QAction(panicQL)
        self.fileExitAction.setShortcut(_fromUtf8(""))
        self.fileExitAction.setProperty("name", _fromUtf8("fileExitAction"))
        self.fileExitAction.setObjectName(_fromUtf8("fileExitAction"))
        self.editUndoAction = QtGui.QAction(panicQL)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../.designer/backup/image5")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editUndoAction.setIcon(icon4)
        self.editUndoAction.setProperty("name", _fromUtf8("editUndoAction"))
        self.editUndoAction.setObjectName(_fromUtf8("editUndoAction"))
        self.editRedoAction = QtGui.QAction(panicQL)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../.designer/backup/image6")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editRedoAction.setIcon(icon5)
        self.editRedoAction.setProperty("name", _fromUtf8("editRedoAction"))
        self.editRedoAction.setObjectName(_fromUtf8("editRedoAction"))
        self.editCutAction = QtGui.QAction(panicQL)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../.designer/backup/image7")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCutAction.setIcon(icon6)
        self.editCutAction.setProperty("name", _fromUtf8("editCutAction"))
        self.editCutAction.setObjectName(_fromUtf8("editCutAction"))
        self.editCopyAction = QtGui.QAction(panicQL)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../.designer/backup/image8")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCopyAction.setIcon(icon7)
        self.editCopyAction.setProperty("name", _fromUtf8("editCopyAction"))
        self.editCopyAction.setObjectName(_fromUtf8("editCopyAction"))
        self.editPasteAction = QtGui.QAction(panicQL)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../.designer/backup/image9")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editPasteAction.setIcon(icon8)
        self.editPasteAction.setProperty("name", _fromUtf8("editPasteAction"))
        self.editPasteAction.setObjectName(_fromUtf8("editPasteAction"))
        self.editFindAction = QtGui.QAction(panicQL)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../.designer/backup/image10")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editFindAction.setIcon(icon9)
        self.editFindAction.setProperty("name", _fromUtf8("editFindAction"))
        self.editFindAction.setObjectName(_fromUtf8("editFindAction"))
        self.helpIndexAction = QtGui.QAction(panicQL)
        self.helpIndexAction.setProperty("name", _fromUtf8("helpIndexAction"))
        self.helpIndexAction.setObjectName(_fromUtf8("helpIndexAction"))
        self.new_menudAction = QtGui.QAction(panicQL)
        self.new_menudAction.setProperty("name", _fromUtf8("new_menudAction"))
        self.new_menudAction.setObjectName(_fromUtf8("new_menudAction"))
        self.calibrationsMaster_FlatAction = QtGui.QAction(panicQL)
        self.calibrationsMaster_FlatAction.setProperty("name", _fromUtf8("calibrationsMaster_FlatAction"))
        self.calibrationsMaster_FlatAction.setObjectName(_fromUtf8("calibrationsMaster_FlatAction"))
        self.calibrationsMaster_Sky_FlatAction = QtGui.QAction(panicQL)
        self.calibrationsMaster_Sky_FlatAction.setProperty("name", _fromUtf8("calibrationsMaster_Sky_FlatAction"))
        self.calibrationsMaster_Sky_FlatAction.setObjectName(_fromUtf8("calibrationsMaster_Sky_FlatAction"))
        self.toolsIRAF_consoleAction = QtGui.QAction(panicQL)
        self.toolsIRAF_consoleAction.setProperty("name", _fromUtf8("toolsIRAF_consoleAction"))
        self.toolsIRAF_consoleAction.setObjectName(_fromUtf8("toolsIRAF_consoleAction"))
        self.toolsDS9_displayAction = QtGui.QAction(panicQL)
        self.toolsDS9_displayAction.setProperty("name", _fromUtf8("toolsDS9_displayAction"))
        self.toolsDS9_displayAction.setObjectName(_fromUtf8("toolsDS9_displayAction"))
        self.toolsAladinAction = QtGui.QAction(panicQL)
        self.toolsAladinAction.setProperty("name", _fromUtf8("toolsAladinAction"))
        self.toolsAladinAction.setObjectName(_fromUtf8("toolsAladinAction"))
        self.fileSearchAction = QtGui.QAction(panicQL)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/edit-find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSearchAction.setIcon(icon10)
        self.fileSearchAction.setProperty("name", _fromUtf8("fileSearchAction"))
        self.fileSearchAction.setObjectName(_fromUtf8("fileSearchAction"))
        self.quitAction = QtGui.QAction(panicQL)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/system-shutdown.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon11)
        self.quitAction.setProperty("name", _fromUtf8("quitAction"))
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.irafConsoleAction = QtGui.QAction(panicQL)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/apps/package_system_shell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.irafConsoleAction.setIcon(icon12)
        self.irafConsoleAction.setProperty("name", _fromUtf8("irafConsoleAction"))
        self.irafConsoleAction.setObjectName(_fromUtf8("irafConsoleAction"))
        self.actionAbout = QtGui.QAction(panicQL)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAladin = QtGui.QAction(panicQL)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("images/aladin_large.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAladin.setIcon(icon13)
        self.actionAladin.setObjectName(_fromUtf8("actionAladin"))
        self.toolBar.addAction(self.fileOpenAction)
        self.toolBar.addAction(self.fileDirAction)
        self.toolBar.addAction(self.fileShow)
        self.toolBar.addAction(self.fileSearchAction)
        self.toolBar.addAction(self.actionAladin)
        self.toolBar.addAction(self.irafConsoleAction)
        self.Toolbar.addAction(self.quitAction)
        self.fileMenu.addAction(self.fileOpenAction)
        self.fileMenu.addAction(self.fileDirAction)
        self.fileMenu.addAction(self.fileShow)
        self.fileMenu.addAction(self.fileSaveAsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileExitAction)
        self.editMenu.addAction(self.editUndoAction)
        self.editMenu.addAction(self.editRedoAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.editCutAction)
        self.editMenu.addAction(self.editCopyAction)
        self.editMenu.addAction(self.editPasteAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.editFindAction)
        self.Calibrations.addAction(self.new_menudAction)
        self.Calibrations.addAction(self.calibrationsMaster_FlatAction)
        self.Calibrations.addAction(self.calibrationsMaster_Sky_FlatAction)
        self.Tools.addAction(self.toolsIRAF_consoleAction)
        self.Tools.addAction(self.toolsDS9_displayAction)
        self.Tools.addAction(self.toolsAladinAction)
        self.helpMenu.addAction(self.helpIndexAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.actionAbout)
        self.MenuBar.addAction(self.fileMenu.menuAction())
        self.MenuBar.addAction(self.editMenu.menuAction())
        self.MenuBar.addAction(self.Settings.menuAction())
        self.MenuBar.addAction(self.Calibrations.menuAction())
        self.MenuBar.addAction(self.Tools.menuAction())
        self.MenuBar.addSeparator()
        self.MenuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(panicQL)
        self.tabWidget3.setCurrentIndex(0)
        self.comboBox_pre_skyWindow.setCurrentIndex(3)
        QtCore.QObject.connect(self.editCopyAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editCopy)
        QtCore.QObject.connect(self.editCutAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editCut)
        QtCore.QObject.connect(self.editFindAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editFind)
        QtCore.QObject.connect(self.editPasteAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editPaste)
        QtCore.QObject.connect(self.editRedoAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editRedo)
        QtCore.QObject.connect(self.editUndoAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editUndo)
        QtCore.QObject.connect(self.fileDirAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileOpen)
        QtCore.QObject.connect(self.fileExitAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileExit)
        QtCore.QObject.connect(self.fileOpenAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.add_slot)
        QtCore.QObject.connect(self.filePrintAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.filePrint)
        QtCore.QObject.connect(self.fileSaveAsAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileSaveAs)
        QtCore.QObject.connect(self.fileShow, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.display_slot)
        QtCore.QObject.connect(self.helpIndexAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.helpIndex)
        QtCore.QObject.connect(self.irafConsoleAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.iraf_console_slot)
        QtCore.QObject.connect(self.quitAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileExit)
        QtCore.QObject.connect(self.toolsAladinAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.start_aladin_slot)
        QtCore.QObject.connect(self.toolsDS9_displayAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.start_ds9_slot)
        QtCore.QObject.connect(self.toolsIRAF_consoleAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.iraf_console_slot)
        QtCore.QObject.connect(self.helpIndexAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.helpIndex)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.helpAbout)
        QtCore.QObject.connect(self.actionAladin, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.start_aladin_slot)
        QtCore.QObject.connect(self.checkBox_autocheck, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.autocheck_slot)
        QtCore.QObject.connect(self.checkBox_outDir_autocheck, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.checkOutDir_slot)
        QtCore.QObject.connect(self.comboBox_classFilter, QtCore.SIGNAL(_fromUtf8("activated(QString)")), panicQL.slot_classFilter)
        QtCore.QObject.connect(self.pushButton_add, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.add_slot)
        QtCore.QObject.connect(self.pushButton_clear, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.clear_mainlist_slot)
        QtCore.QObject.connect(self.pushButton_createMDark, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.createMasterDark_slot)
        QtCore.QObject.connect(self.pushButton_master_dark, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_masteDark_slot)
        QtCore.QObject.connect(self.pushButton_master_mask, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_masterMask_slot)
        QtCore.QObject.connect(self.pushButton_file_filter, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.filename_filter_slot)
        QtCore.QObject.connect(self.pushButton_DomeF_add, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setDFlats_slot)
        QtCore.QObject.connect(self.pushButton_Darks_add, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setDarks_slot)
        QtCore.QObject.connect(self.pushButton_dataSourceD, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setDataSourceDir_slot)
        QtCore.QObject.connect(self.pushButton_remove, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.del_slot)
        QtCore.QObject.connect(self.pushButton_outputD, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setOutputDir_slot)
        QtCore.QObject.connect(self.pushButton_master_flat, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_masterFlat_slot)
        QtCore.QObject.connect(self.pushButton_start_proc, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_start_stop_slot)
        QtCore.QObject.connect(self.pushButton_SkyF_add, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setSFlat_slot)
        QtCore.QObject.connect(self.pushButton_createCalibs, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.createCalibs_slot)
        QtCore.QObject.connect(self.pushButton_subtract_last2, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_subtract_last2_slot)
        QtCore.QObject.connect(self.checkBox_pre_appSF, QtCore.SIGNAL(_fromUtf8("clicked()")), self.checkBox_pre_subD.toggle)
        QtCore.QObject.connect(self.checkBox_pre_appSF, QtCore.SIGNAL(_fromUtf8("clicked()")), self.checkBox_pre_appMF.toggle)
        QtCore.QObject.connect(self.checkBox_pre_appMF, QtCore.SIGNAL(_fromUtf8("clicked()")), self.checkBox_pre_appSF.toggle)
        QtCore.QObject.connect(self.pushButton_test1, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.testSlot)
        QtCore.QObject.connect(self.pushButton_tempD, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setTempDir_slot)
        QtCore.QObject.connect(self.checkBox_data_grouping_OT, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.data_grouping_slot)
        QtCore.QMetaObject.connectSlotsByName(panicQL)

    def retranslateUi(self, panicQL):
        panicQL.setWindowTitle(QtGui.QApplication.translate("panicQL", "PANIC QuickLook", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_7_2.setText(QtGui.QApplication.translate("panicQL", "<font color=\"#1759ff\">Event log (Time UTC)</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_autocheck.setToolTip(QtGui.QApplication.translate("panicQL", "Autocheck for new incoming images", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_outDir_autocheck.setToolTip(QtGui.QApplication.translate("panicQL", "Autocheck for new incoming images", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_3.setText(QtGui.QApplication.translate("panicQL", "Check", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove.setToolTip(QtGui.QApplication.translate("panicQL", "Remove data file from the list view, but keeping on disk", "Remove data file from the list view, but keeping on disk", QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove.setText(QtGui.QApplication.translate("panicQL", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add.setText(QtGui.QApplication.translate("panicQL", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear.setToolTip(QtGui.QApplication.translate("panicQL", "Clear list view panel, but not files on disk", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_clear.setText(QtGui.QApplication.translate("panicQL", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel2_3.setText(QtGui.QApplication.translate("panicQL", "Last file received:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dataSourceD.setToolTip(QtGui.QApplication.translate("panicQL", "Select a directory or log file for received files location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_dataSourceD.setText(QtGui.QApplication.translate("panicQL", "Input Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_outputD.setToolTip(QtGui.QApplication.translate("panicQL", "Generated files location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_outputD.setToolTip(QtGui.QApplication.translate("panicQL", "Browse the output processed files location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_outputD.setText(QtGui.QApplication.translate("panicQL", "Output Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_file_filter.setText(QtGui.QApplication.translate("panicQL", "Set Filename Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_createCalibs.setText(QtGui.QApplication.translate("panicQL", "Create Calibrations", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_2_3.setText(QtGui.QApplication.translate("panicQL", "Data List View", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_2.setText(QtGui.QApplication.translate("panicQL", "List View Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setToolTip(QtGui.QApplication.translate("panicQL", "Filter data sources list using its class/type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(0, QtGui.QApplication.translate("panicQL", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(1, QtGui.QApplication.translate("panicQL", "DARK", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(2, QtGui.QApplication.translate("panicQL", "DOME_FLAT", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(3, QtGui.QApplication.translate("panicQL", "SKY_FLAT", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(4, QtGui.QApplication.translate("panicQL", "SCIENCE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(5, QtGui.QApplication.translate("panicQL", "REDUCED", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(6, QtGui.QApplication.translate("panicQL", "GROUP", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_classFilter.setItemText(7, QtGui.QApplication.translate("panicQL", "OUTS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_QL_Mode.setToolTip(QtGui.QApplication.translate("panicQL", "Filter data sources list using its class/type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_QL_Mode.setItemText(0, QtGui.QApplication.translate("panicQL", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_QL_Mode.setItemText(1, QtGui.QApplication.translate("panicQL", "Lazy", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_QL_Mode.setItemText(2, QtGui.QApplication.translate("panicQL", "Pre-reduction", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_QL_Mode.setItemText(3, QtGui.QApplication.translate("panicQL", "UserDef_1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_QL_Mode.setItemText(4, QtGui.QApplication.translate("panicQL", "UserDef_2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_QL_Mode.setItemText(5, QtGui.QApplication.translate("panicQL", "UserDef_3", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_2_2.setText(QtGui.QApplication.translate("panicQL", "QL Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start_proc.setText(QtGui.QApplication.translate("panicQL", "START processing", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_subtract_last2.setText(QtGui.QApplication.translate("panicQL", "Subtract-Last2", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_sourceD.setToolTip(QtGui.QApplication.translate("panicQL", "Received files location", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_filename_filter.setText(QtGui.QApplication.translate("panicQL", "*.fits", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.setSortingEnabled(True)
        self.listView_dataS.headerItem().setText(0, QtGui.QApplication.translate("panicQL", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.headerItem().setText(1, QtGui.QApplication.translate("panicQL", "ImageType", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.headerItem().setText(2, QtGui.QApplication.translate("panicQL", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.headerItem().setText(3, QtGui.QApplication.translate("panicQL", "ExpT", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.headerItem().setText(4, QtGui.QApplication.translate("panicQL", "Date-Obs", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.headerItem().setText(5, QtGui.QApplication.translate("panicQL", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.headerItem().setText(6, QtGui.QApplication.translate("panicQL", "RA", None, QtGui.QApplication.UnicodeUTF8))
        self.listView_dataS.headerItem().setText(7, QtGui.QApplication.translate("panicQL", "Dec", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_queue_size.setText(QtGui.QApplication.translate("panicQL", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("panicQL", "#Tasks in the queue", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab), QtGui.QApplication.translate("panicQL", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("panicQL", "Common Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("panicQL", "Check header", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox7_2_2_2.setText(QtGui.QApplication.translate("panicQL", "Create Log file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tempD.setToolTip(QtGui.QApplication.translate("panicQL", "Browse the temporal file location", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_tempD.setText(QtGui.QApplication.translate("panicQL", "Temporary Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_tempD.setToolTip(QtGui.QApplication.translate("panicQL", "Temporal files location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("panicQL", "Data Grouping", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5.setText(QtGui.QApplication.translate("panicQL", "arcsecs", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5_2.setText(QtGui.QApplication.translate("panicQL", "secs", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_data_grouping_OT.setText(QtGui.QApplication.translate("panicQL", "OT Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel5_3.setText(QtGui.QApplication.translate("panicQL", "files", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_3.setText(QtGui.QApplication.translate("panicQL", "RA,Dec offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_3_2.setText(QtGui.QApplication.translate("panicQL", "Time offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_3_3.setText(QtGui.QApplication.translate("panicQL", "Max. num.files", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ra_dec_near_offset.setInputMask(QtGui.QApplication.translate("panicQL", "#####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_ra_dec_near_offset.setText(QtGui.QApplication.translate("panicQL", "600", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_time_near_offset.setInputMask(QtGui.QApplication.translate("panicQL", "#####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_time_near_offset.setText(QtGui.QApplication.translate("panicQL", "900", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_max_num_files.setInputMask(QtGui.QApplication.translate("panicQL", "####; ", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_max_num_files.setText(QtGui.QApplication.translate("panicQL", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("panicQL", "Astrometry", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_AstromCatalog.setItemText(0, QtGui.QApplication.translate("panicQL", "2MASS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_AstromCatalog.setItemText(1, QtGui.QApplication.translate("panicQL", "USNO-B1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_AstromCatalog.setItemText(2, QtGui.QApplication.translate("panicQL", "GSC 2.2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_AstromCatalog.setItemText(3, QtGui.QApplication.translate("panicQL", "SDSS-R5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_AstromCatalog.setItemText(4, QtGui.QApplication.translate("panicQL", "UCAC-2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_AstromCatalog.setItemText(5, QtGui.QApplication.translate("panicQL", "FILE", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_doRegrig.setText(QtGui.QApplication.translate("panicQL", "Apply (re-grid)", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_2.setText(QtGui.QApplication.translate("panicQL", "Catalog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_LazyMode.setTitle(QtGui.QApplication.translate("panicQL", "Lazy Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_show_imgs.setText(QtGui.QApplication.translate("panicQL", "Only display image", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_subDark.setText(QtGui.QApplication.translate("panicQL", "Dark subtraction", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_appBPM.setText(QtGui.QApplication.translate("panicQL", "Apply Bad Pixel Mask (BPM)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_appFlat.setText(QtGui.QApplication.translate("panicQL", "Flat-Fielding", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_subLastFrame.setText(QtGui.QApplication.translate("panicQL", "Subtract last frame (science)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_subSky.setText(QtGui.QApplication.translate("panicQL", "Subtract nearest sky", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_appSAstrom.setText(QtGui.QApplication.translate("panicQL", "Apply \'static\' Astrometry", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_PrereductionMode.setTitle(QtGui.QApplication.translate("panicQL", "Pre-Reduction Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pre_skyWindow.setItemText(0, QtGui.QApplication.translate("panicQL", "1-Current frame", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pre_skyWindow.setItemText(1, QtGui.QApplication.translate("panicQL", "2-frames", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pre_skyWindow.setItemText(2, QtGui.QApplication.translate("panicQL", "3-frames", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pre_skyWindow.setItemText(3, QtGui.QApplication.translate("panicQL", "4-frames", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pre_skyWindow.setItemText(4, QtGui.QApplication.translate("panicQL", "5-frames", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pre_QM.setText(QtGui.QApplication.translate("panicQL", "Quality measurements  (background, psf, ....)", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3.setText(QtGui.QApplication.translate("panicQL", "# sky nearest frames", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pre_MA.setText(QtGui.QApplication.translate("panicQL", "Make Astrometry", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pre_compDM.setText(QtGui.QApplication.translate("panicQL", "Compute distortion map", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pre_subD.setText(QtGui.QApplication.translate("panicQL", "Substract dark", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pre_appMF.setText(QtGui.QApplication.translate("panicQL", "Apply Master Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pre_appSF.setText(QtGui.QApplication.translate("panicQL", "Apply SuperFlat", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pre_BS.setText(QtGui.QApplication.translate("panicQL", "Build stacked image", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.TabPage), QtGui.QApplication.translate("panicQL", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Darks_add.setText(QtGui.QApplication.translate("panicQL", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DomeF_add.setText(QtGui.QApplication.translate("panicQL", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SkyF_add.setText(QtGui.QApplication.translate("panicQL", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Darks_del.setText(QtGui.QApplication.translate("panicQL", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DFlat_del.setText(QtGui.QApplication.translate("panicQL", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SFlat_del.setText(QtGui.QApplication.translate("panicQL", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel3_2.setText(QtGui.QApplication.translate("panicQL", "<b>Filter</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_master_mask.setText(QtGui.QApplication.translate("panicQL", "Master Mask...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_master_flat.setText(QtGui.QApplication.translate("panicQL", "Master Flat...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_master_dark.setText(QtGui.QApplication.translate("panicQL", "Master Dark...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_createMDark.setText(QtGui.QApplication.translate("panicQL", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4.setText(QtGui.QApplication.translate("panicQL", "<b>Dark</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_createMDF.setText(QtGui.QApplication.translate("panicQL", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_createMSF.setText(QtGui.QApplication.translate("panicQL", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4_2.setText(QtGui.QApplication.translate("panicQL", "<b>Dome Flat</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_4_2_2.setText(QtGui.QApplication.translate("panicQL", "<b>Sky Flat</b>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_test1.setText(QtGui.QApplication.translate("panicQL", "Test1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab1), QtGui.QApplication.translate("panicQL", "Calibrations", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel1_7.setText(QtGui.QApplication.translate("panicQL", "<font color=\"#1759ff\">Times in UTC</font>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.TabPage1), QtGui.QApplication.translate("panicQL", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setProperty("label", QtGui.QApplication.translate("panicQL", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.Toolbar.setProperty("label", QtGui.QApplication.translate("panicQL", "Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.fileMenu.setTitle(QtGui.QApplication.translate("panicQL", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.editMenu.setTitle(QtGui.QApplication.translate("panicQL", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.Settings.setTitle(QtGui.QApplication.translate("panicQL", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.Calibrations.setTitle(QtGui.QApplication.translate("panicQL", "Calibrations", None, QtGui.QApplication.UnicodeUTF8))
        self.Tools.setTitle(QtGui.QApplication.translate("panicQL", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("panicQL", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setText(QtGui.QApplication.translate("panicQL", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setIconText(QtGui.QApplication.translate("panicQL", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setToolTip(QtGui.QApplication.translate("panicQL", "Add a new file to \'Data List View\'", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDirAction.setText(QtGui.QApplication.translate("panicQL", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDirAction.setIconText(QtGui.QApplication.translate("panicQL", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDirAction.setToolTip(QtGui.QApplication.translate("panicQL", "Change data source directory", None, QtGui.QApplication.UnicodeUTF8))
        self.fileDirAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.fileShow.setText(QtGui.QApplication.translate("panicQL", "&Show", None, QtGui.QApplication.UnicodeUTF8))
        self.fileShow.setIconText(QtGui.QApplication.translate("panicQL", "Show", None, QtGui.QApplication.UnicodeUTF8))
        self.fileShow.setToolTip(QtGui.QApplication.translate("panicQL", "Show image", None, QtGui.QApplication.UnicodeUTF8))
        self.fileShow.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAsAction.setText(QtGui.QApplication.translate("panicQL", "Save &As...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSaveAsAction.setIconText(QtGui.QApplication.translate("panicQL", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.filePrintAction.setText(QtGui.QApplication.translate("panicQL", "&Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.filePrintAction.setIconText(QtGui.QApplication.translate("panicQL", "Print", None, QtGui.QApplication.UnicodeUTF8))
        self.filePrintAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setText(QtGui.QApplication.translate("panicQL", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setIconText(QtGui.QApplication.translate("panicQL", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setText(QtGui.QApplication.translate("panicQL", "&Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setIconText(QtGui.QApplication.translate("panicQL", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.editUndoAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setText(QtGui.QApplication.translate("panicQL", "&Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setIconText(QtGui.QApplication.translate("panicQL", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.editRedoAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+Y", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setText(QtGui.QApplication.translate("panicQL", "Cu&t", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setIconText(QtGui.QApplication.translate("panicQL", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.editCutAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setText(QtGui.QApplication.translate("panicQL", "&Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setIconText(QtGui.QApplication.translate("panicQL", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.editCopyAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setText(QtGui.QApplication.translate("panicQL", "&Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setIconText(QtGui.QApplication.translate("panicQL", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.editPasteAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.editFindAction.setText(QtGui.QApplication.translate("panicQL", "&Find...", None, QtGui.QApplication.UnicodeUTF8))
        self.editFindAction.setIconText(QtGui.QApplication.translate("panicQL", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.editFindAction.setShortcut(QtGui.QApplication.translate("panicQL", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.helpIndexAction.setText(QtGui.QApplication.translate("panicQL", "&Index...", None, QtGui.QApplication.UnicodeUTF8))
        self.helpIndexAction.setIconText(QtGui.QApplication.translate("panicQL", "Index", None, QtGui.QApplication.UnicodeUTF8))
        self.helpIndexAction.setShortcut(QtGui.QApplication.translate("panicQL", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.new_menudAction.setText(QtGui.QApplication.translate("panicQL", "Master Dark", None, QtGui.QApplication.UnicodeUTF8))
        self.new_menudAction.setIconText(QtGui.QApplication.translate("panicQL", "Master Dark", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrationsMaster_FlatAction.setText(QtGui.QApplication.translate("panicQL", "Master Dome-Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrationsMaster_FlatAction.setIconText(QtGui.QApplication.translate("panicQL", "Master Dome-Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrationsMaster_Sky_FlatAction.setText(QtGui.QApplication.translate("panicQL", "Master Sky-Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrationsMaster_Sky_FlatAction.setIconText(QtGui.QApplication.translate("panicQL", "Master Sky-Flat", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsIRAF_consoleAction.setText(QtGui.QApplication.translate("panicQL", "IRAF console", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsIRAF_consoleAction.setIconText(QtGui.QApplication.translate("panicQL", "IRAF console", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsDS9_displayAction.setText(QtGui.QApplication.translate("panicQL", "DS9 display", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsDS9_displayAction.setIconText(QtGui.QApplication.translate("panicQL", "DS9 display", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsAladinAction.setText(QtGui.QApplication.translate("panicQL", "Aladin", None, QtGui.QApplication.UnicodeUTF8))
        self.toolsAladinAction.setIconText(QtGui.QApplication.translate("panicQL", "Aladin", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSearchAction.setIconText(QtGui.QApplication.translate("panicQL", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.fileSearchAction.setToolTip(QtGui.QApplication.translate("panicQL", "Search files", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setIconText(QtGui.QApplication.translate("panicQL", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.quitAction.setToolTip(QtGui.QApplication.translate("panicQL", "Quit Quick-Look", None, QtGui.QApplication.UnicodeUTF8))
        self.irafConsoleAction.setIconText(QtGui.QApplication.translate("panicQL", "Action", None, QtGui.QApplication.UnicodeUTF8))
        self.irafConsoleAction.setToolTip(QtGui.QApplication.translate("panicQL", "Open an IRAF console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("panicQL", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAladin.setText(QtGui.QApplication.translate("panicQL", "Aladin", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAladin.setToolTip(QtGui.QApplication.translate("panicQL", "Open Aladin application", None, QtGui.QApplication.UnicodeUTF8))

