# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/panic/DEVELOP/papi/QL4/panicQL.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_panicQL(object):
    def setupUi(self, panicQL):
        panicQL.setObjectName(_fromUtf8("panicQL"))
        panicQL.resize(961, 729)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/my_icon/images/logo_PANIC_100.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        panicQL.setWindowIcon(icon)
        self.widget = QtGui.QWidget(panicQL)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.textLabel1_7_2 = QtGui.QLabel(self.widget)
        self.textLabel1_7_2.setGeometry(QtCore.QRect(14, 458, 220, 22))
        self.textLabel1_7_2.setWordWrap(False)
        self.textLabel1_7_2.setObjectName(_fromUtf8("textLabel1_7_2"))
        self.tabWidget3 = QtGui.QTabWidget(self.widget)
        self.tabWidget3.setEnabled(True)
        self.tabWidget3.setGeometry(QtCore.QRect(5, 0, 940, 460))
        self.tabWidget3.setObjectName(_fromUtf8("tabWidget3"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.checkBox_autocheck = QtGui.QCheckBox(self.tab)
        self.checkBox_autocheck.setGeometry(QtCore.QRect(440, 31, 20, 20))
        self.checkBox_autocheck.setText(_fromUtf8(""))
        self.checkBox_autocheck.setChecked(False)
        self.checkBox_autocheck.setObjectName(_fromUtf8("checkBox_autocheck"))
        self.checkBox_outDir_autocheck = QtGui.QCheckBox(self.tab)
        self.checkBox_outDir_autocheck.setGeometry(QtCore.QRect(441, 64, 20, 20))
        self.checkBox_outDir_autocheck.setText(_fromUtf8(""))
        self.checkBox_outDir_autocheck.setObjectName(_fromUtf8("checkBox_outDir_autocheck"))
        self.textLabel1_3 = QtGui.QLabel(self.tab)
        self.textLabel1_3.setGeometry(QtCore.QRect(430, 10, 50, 20))
        self.textLabel1_3.setWordWrap(False)
        self.textLabel1_3.setObjectName(_fromUtf8("textLabel1_3"))
        self.pushButton_remove = QtGui.QPushButton(self.tab)
        self.pushButton_remove.setGeometry(QtCore.QRect(755, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setObjectName(_fromUtf8("pushButton_remove"))
        self.pushButton_add = QtGui.QPushButton(self.tab)
        self.pushButton_add.setGeometry(QtCore.QRect(671, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.pixmapLabel1_2 = QtGui.QLabel(self.tab)
        self.pixmapLabel1_2.setGeometry(QtCore.QRect(767, 25, 81, 71))
        self.pixmapLabel1_2.setPixmap(QtGui.QPixmap(_fromUtf8("../../../.designer/backup/images/logo_PANIC.jpg")))
        self.pixmapLabel1_2.setScaledContents(True)
        self.pixmapLabel1_2.setWordWrap(False)
        self.pixmapLabel1_2.setObjectName(_fromUtf8("pixmapLabel1_2"))
        self.pushButton_clear = QtGui.QPushButton(self.tab)
        self.pushButton_clear.setGeometry(QtCore.QRect(843, 390, 70, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName(_fromUtf8("pushButton_clear"))
        self.textLabel2_3 = QtGui.QLabel(self.tab)
        self.textLabel2_3.setGeometry(QtCore.QRect(10, 390, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel2_3.setFont(font)
        self.textLabel2_3.setWordWrap(False)
        self.textLabel2_3.setObjectName(_fromUtf8("textLabel2_3"))
        self.lineEdit_last_file = QtGui.QLineEdit(self.tab)
        self.lineEdit_last_file.setGeometry(QtCore.QRect(140, 390, 311, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_last_file.setPalette(palette)
        self.lineEdit_last_file.setReadOnly(True)
        self.lineEdit_last_file.setObjectName(_fromUtf8("lineEdit_last_file"))
        self.pushButton_dataSourceD = QtGui.QPushButton(self.tab)
        self.pushButton_dataSourceD.setGeometry(QtCore.QRect(19, 27, 110, 23))
        self.pushButton_dataSourceD.setObjectName(_fromUtf8("pushButton_dataSourceD"))
        self.lineEdit_outputD = QtGui.QLineEdit(self.tab)
        self.lineEdit_outputD.setGeometry(QtCore.QRect(141, 63, 290, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_outputD.setPalette(palette)
        self.lineEdit_outputD.setReadOnly(True)
        self.lineEdit_outputD.setObjectName(_fromUtf8("lineEdit_outputD"))
        self.pushButton_outputD = QtGui.QPushButton(self.tab)
        self.pushButton_outputD.setGeometry(QtCore.QRect(19, 61, 110, 23))
        self.pushButton_outputD.setObjectName(_fromUtf8("pushButton_outputD"))
        self.pushButton_file_filter = QtGui.QPushButton(self.tab)
        self.pushButton_file_filter.setGeometry(QtCore.QRect(609, 30, 131, 23))
        self.pushButton_file_filter.setObjectName(_fromUtf8("pushButton_file_filter"))
        self.pushButton_createCalibs = QtGui.QPushButton(self.tab)
        self.pushButton_createCalibs.setGeometry(QtCore.QRect(770, 110, 140, 23))
        self.pushButton_createCalibs.setObjectName(_fromUtf8("pushButton_createCalibs"))
        self.textLabel4_2_3 = QtGui.QLabel(self.tab)
        self.textLabel4_2_3.setGeometry(QtCore.QRect(20, 150, 110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2_3.setFont(font)
        self.textLabel4_2_3.setWordWrap(False)
        self.textLabel4_2_3.setObjectName(_fromUtf8("textLabel4_2_3"))
        self.textLabel4_2 = QtGui.QLabel(self.tab)
        self.textLabel4_2.setGeometry(QtCore.QRect(18, 101, 110, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2.setFont(font)
        self.textLabel4_2.setWordWrap(False)
        self.textLabel4_2.setObjectName(_fromUtf8("textLabel4_2"))
        self.comboBox_classFilter = QtGui.QComboBox(self.tab)
        self.comboBox_classFilter.setGeometry(QtCore.QRect(18, 121, 110, 21))
        self.comboBox_classFilter.setObjectName(_fromUtf8("comboBox_classFilter"))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_classFilter.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode = QtGui.QComboBox(self.tab)
        self.comboBox_QL_Mode.setGeometry(QtCore.QRect(154, 121, 110, 21))
        self.comboBox_QL_Mode.setObjectName(_fromUtf8("comboBox_QL_Mode"))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.comboBox_QL_Mode.addItem(_fromUtf8(""))
        self.textLabel4_2_2 = QtGui.QLabel(self.tab)
        self.textLabel4_2_2.setGeometry(QtCore.QRect(160, 100, 80, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel4_2_2.setFont(font)
        self.textLabel4_2_2.setWordWrap(False)
        self.textLabel4_2_2.setObjectName(_fromUtf8("textLabel4_2_2"))
        self.pushButton_start_proc = QtGui.QPushButton(self.tab)
        self.pushButton_start_proc.setGeometry(QtCore.QRect(770, 140, 140, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 192, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 160, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 64, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_start_proc.setPalette(palette)
        self.pushButton_start_proc.setObjectName(_fromUtf8("pushButton_start_proc"))
        self.pushButton_subtract_last2 = QtGui.QPushButton(self.tab)
        self.pushButton_subtract_last2.setGeometry(QtCore.QRect(650, 139, 111, 24))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(207, 136, 86))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_subtract_last2.setPalette(palette)
        self.pushButton_subtract_last2.setObjectName(_fromUtf8("pushButton_subtract_last2"))
        self.lineEdit_sourceD = QtGui.QLineEdit(self.tab)
        self.lineEdit_sourceD.setGeometry(QtCore.QRect(140, 30, 290, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_sourceD.setPalette(palette)
        self.lineEdit_sourceD.setReadOnly(True)
        self.lineEdit_sourceD.setObjectName(_fromUtf8("lineEdit_sourceD"))
        self.lineEdit_filename_filter = QtGui.QLineEdit(self.tab)
        self.lineEdit_filename_filter.setGeometry(QtCore.QRect(536, 30, 60, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_filename_filter.setPalette(palette)
        self.lineEdit_filename_filter.setAlignment(QtCore.Qt.AlignRight)
        self.lineEdit_filename_filter.setReadOnly(True)
        self.lineEdit_filename_filter.setObjectName(_fromUtf8("lineEdit_filename_filter"))
        self.listView_dataS = QtGui.QTreeWidget(self.tab)
        self.listView_dataS.setGeometry(QtCore.QRect(10, 170, 911, 211))
        self.listView_dataS.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listView_dataS.setObjectName(_fromUtf8("listView_dataS"))
        self.listView_dataS.header().setStretchLastSection(True)
        self.lineEdit_queue_size = QtGui.QLineEdit(self.tab)
        self.lineEdit_queue_size.setGeometry(QtCore.QRect(536, 64, 60, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_queue_size.setPalette(palette)
        self.lineEdit_queue_size.setAlignment(QtCore.Qt.AlignRight)
        self.lineEdit_queue_size.setReadOnly(True)
        self.lineEdit_queue_size.setObjectName(_fromUtf8("lineEdit_queue_size"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(605, 65, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(810, 20, 91, 71))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(84, 84))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.checkBox_geirsFile = QtGui.QCheckBox(self.tab)
        self.checkBox_geirsFile.setGeometry(QtCore.QRect(140, 10, 20, 20))
        self.checkBox_geirsFile.setText(_fromUtf8(""))
        self.checkBox_geirsFile.setChecked(False)
        self.checkBox_geirsFile.setObjectName(_fromUtf8("checkBox_geirsFile"))
        self.textLabel1_5 = QtGui.QLabel(self.tab)
        self.textLabel1_5.setGeometry(QtCore.QRect(160, 10, 91, 20))
        self.textLabel1_5.setWordWrap(False)
        self.textLabel1_5.setObjectName(_fromUtf8("textLabel1_5"))
        self.checkBox_currentNight = QtGui.QCheckBox(self.tab)
        self.checkBox_currentNight.setGeometry(QtCore.QRect(275, 10, 20, 20))
        self.checkBox_currentNight.setText(_fromUtf8(""))
        self.checkBox_currentNight.setChecked(False)
        self.checkBox_currentNight.setObjectName(_fromUtf8("checkBox_currentNight"))
        self.textLabel1_6 = QtGui.QLabel(self.tab)
        self.textLabel1_6.setGeometry(QtCore.QRect(295, 10, 101, 20))
        self.textLabel1_6.setWordWrap(False)
        self.textLabel1_6.setObjectName(_fromUtf8("textLabel1_6"))
        self.tabWidget3.addTab(self.tab, _fromUtf8(""))
        self.TabPage = QtGui.QWidget()
        self.TabPage.setObjectName(_fromUtf8("TabPage"))
        self.groupBox = QtGui.QGroupBox(self.TabPage)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 181, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox = QtGui.QCheckBox(self.groupBox)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox7_2_2_2 = QtGui.QCheckBox(self.groupBox)
        self.checkBox7_2_2_2.setChecked(True)
        self.checkBox7_2_2_2.setObjectName(_fromUtf8("checkBox7_2_2_2"))
        self.verticalLayout_2.addWidget(self.checkBox7_2_2_2)
        self.pushButton_tempD = QtGui.QPushButton(self.groupBox)
        self.pushButton_tempD.setObjectName(_fromUtf8("pushButton_tempD"))
        self.verticalLayout_2.addWidget(self.pushButton_tempD)
        self.lineEdit_tempD = QtGui.QLineEdit(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_tempD.setPalette(palette)
        self.lineEdit_tempD.setReadOnly(True)
        self.lineEdit_tempD.setObjectName(_fromUtf8("lineEdit_tempD"))
        self.verticalLayout_2.addWidget(self.lineEdit_tempD)
        self.groupBox_2 = QtGui.QGroupBox(self.TabPage)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 10, 421, 131))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.textLabel5 = QtGui.QLabel(self.groupBox_2)
        self.textLabel5.setGeometry(QtCore.QRect(192, 22, 58, 20))
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName(_fromUtf8("textLabel5"))
        self.textLabel5_2 = QtGui.QLabel(self.groupBox_2)
        self.textLabel5_2.setGeometry(QtCore.QRect(192, 45, 58, 20))
        self.textLabel5_2.setMidLineWidth(1)
        self.textLabel5_2.setWordWrap(False)
        self.textLabel5_2.setObjectName(_fromUtf8("textLabel5_2"))
        self.checkBox_data_grouping_OT = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_data_grouping_OT.setGeometry(QtCore.QRect(260, 70, 140, 19))
        self.checkBox_data_grouping_OT.setChecked(False)
        self.checkBox_data_grouping_OT.setObjectName(_fromUtf8("checkBox_data_grouping_OT"))
        self.textLabel5_3 = QtGui.QLabel(self.groupBox_2)
        self.textLabel5_3.setGeometry(QtCore.QRect(192, 70, 58, 20))
        self.textLabel5_3.setMidLineWidth(1)
        self.textLabel5_3.setWordWrap(False)
        self.textLabel5_3.setObjectName(_fromUtf8("textLabel5_3"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 93, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textLabel4_3 = QtGui.QLabel(self.layoutWidget)
        self.textLabel4_3.setWordWrap(False)
        self.textLabel4_3.setObjectName(_fromUtf8("textLabel4_3"))
        self.verticalLayout_3.addWidget(self.textLabel4_3)
        self.textLabel4_3_2 = QtGui.QLabel(self.layoutWidget)
        self.textLabel4_3_2.setWordWrap(False)
        self.textLabel4_3_2.setObjectName(_fromUtf8("textLabel4_3_2"))
        self.verticalLayout_3.addWidget(self.textLabel4_3_2)
        self.textLabel4_3_3 = QtGui.QLabel(self.layoutWidget)
        self.textLabel4_3_3.setWordWrap(False)
        self.textLabel4_3_3.setObjectName(_fromUtf8("textLabel4_3_3"))
        self.verticalLayout_3.addWidget(self.textLabel4_3_3)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 20, 61, 76))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit_ra_dec_near_offset = QtGui.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_ra_dec_near_offset.setPalette(palette)
        self.lineEdit_ra_dec_near_offset.setObjectName(_fromUtf8("lineEdit_ra_dec_near_offset"))
        self.verticalLayout_4.addWidget(self.lineEdit_ra_dec_near_offset)
        self.lineEdit_time_near_offset = QtGui.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_time_near_offset.setPalette(palette)
        self.lineEdit_time_near_offset.setObjectName(_fromUtf8("lineEdit_time_near_offset"))
        self.verticalLayout_4.addWidget(self.lineEdit_time_near_offset)
        self.lineEdit_max_num_files = QtGui.QLineEdit(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit_max_num_files.setPalette(palette)
        self.lineEdit_max_num_files.setObjectName(_fromUtf8("lineEdit_max_num_files"))
        self.verticalLayout_4.addWidget(self.lineEdit_max_num_files)
        self.groupBox_3 = QtGui.QGroupBox(self.TabPage)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 10, 251, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_AstromCatalog = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_AstromCatalog.setGeometry(QtCore.QRect(20, 40, 90, 21))
        self.comboBox_AstromCatalog.setObjectName(_fromUtf8("comboBox_AstromCatalog"))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.comboBox_AstromCatalog.addItem(_fromUtf8(""))
        self.textLabel1_2 = QtGui.QLabel(self.groupBox_3)
        self.textLabel1_2.setGeometry(QtCore.QRect(20, 20, 58, 20))
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName(_fromUtf8("textLabel1_2"))
        self.groupBox_LazyMode = QtGui.QGroupBox(self.TabPage)
        self.groupBox_LazyMode.setGeometry(QtCore.QRect(20, 251, 271, 171))
        self.groupBox_LazyMode.setObjectName(_fromUtf8("groupBox_LazyMode"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_LazyMode)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox_subDark_FF_BPM = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subDark_FF_BPM.setChecked(False)
        self.checkBox_subDark_FF_BPM.setAutoExclusive(True)
        self.checkBox_subDark_FF_BPM.setObjectName(_fromUtf8("checkBox_subDark_FF_BPM"))
        self.verticalLayout.addWidget(self.checkBox_subDark_FF_BPM)
        self.checkBox_subLastFrame = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subLastFrame.setAutoExclusive(True)
        self.checkBox_subLastFrame.setObjectName(_fromUtf8("checkBox_subLastFrame"))
        self.verticalLayout.addWidget(self.checkBox_subLastFrame)
        self.checkBox_subSky = QtGui.QCheckBox(self.groupBox_LazyMode)
        self.checkBox_subSky.setEnabled(True)
        self.checkBox_subSky.setAutoExclusive(True)
        self.checkBox_subSky.setObjectName(_fromUtf8("checkBox_subSky"))
        self.verticalLayout.addWidget(self.checkBox_subSky)
        self.groupBox_PrereductionMode = QtGui.QGroupBox(self.TabPage)
        self.groupBox_PrereductionMode.setGeometry(QtCore.QRect(310, 152, 601, 271))
        self.groupBox_PrereductionMode.setObjectName(_fromUtf8("groupBox_PrereductionMode"))
        self.comboBox_pre_skyWindow = QtGui.QComboBox(self.groupBox_PrereductionMode)
        self.comboBox_pre_skyWindow.setGeometry(QtCore.QRect(30, 190, 118, 21))
        self.comboBox_pre_skyWindow.setObjectName(_fromUtf8("comboBox_pre_skyWindow"))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.comboBox_pre_skyWindow.addItem(_fromUtf8(""))
        self.checkBox_pre_QM = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_QM.setEnabled(False)
        self.checkBox_pre_QM.setGeometry(QtCore.QRect(260, 70, 311, 19))
        self.checkBox_pre_QM.setChecked(True)
        self.checkBox_pre_QM.setObjectName(_fromUtf8("checkBox_pre_QM"))
        self.textLabel3 = QtGui.QLabel(self.groupBox_PrereductionMode)
        self.textLabel3.setGeometry(QtCore.QRect(30, 170, 151, 16))
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName(_fromUtf8("textLabel3"))
        self.checkBox_pre_MA = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_MA.setEnabled(False)
        self.checkBox_pre_MA.setGeometry(QtCore.QRect(260, 40, 180, 19))
        self.checkBox_pre_MA.setChecked(True)
        self.checkBox_pre_MA.setObjectName(_fromUtf8("checkBox_pre_MA"))
        self.checkBox_pre_appBPM = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appBPM.setGeometry(QtCore.QRect(30, 100, 180, 19))
        self.checkBox_pre_appBPM.setChecked(False)
        self.checkBox_pre_appBPM.setObjectName(_fromUtf8("checkBox_pre_appBPM"))
        self.checkBox_pre_subDark_FF = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_subDark_FF.setGeometry(QtCore.QRect(30, 40, 180, 19))
        self.checkBox_pre_subDark_FF.setChecked(False)
        self.checkBox_pre_subDark_FF.setObjectName(_fromUtf8("checkBox_pre_subDark_FF"))
        self.checkBox_pre_appSF = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appSF.setGeometry(QtCore.QRect(30, 70, 180, 19))
        self.checkBox_pre_appSF.setChecked(True)
        self.checkBox_pre_appSF.setObjectName(_fromUtf8("checkBox_pre_appSF"))
        self.checkBox_pre_BS = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_BS.setEnabled(False)
        self.checkBox_pre_BS.setGeometry(QtCore.QRect(260, 100, 171, 19))
        self.checkBox_pre_BS.setChecked(True)
        self.checkBox_pre_BS.setObjectName(_fromUtf8("checkBox_pre_BS"))
        self.checkBox_pre_appNLC = QtGui.QCheckBox(self.groupBox_PrereductionMode)
        self.checkBox_pre_appNLC.setGeometry(QtCore.QRect(30, 130, 181, 19))
        self.checkBox_pre_appNLC.setChecked(False)
        self.checkBox_pre_appNLC.setObjectName(_fromUtf8("checkBox_pre_appNLC"))
        self.comboBox_detector = QtGui.QComboBox(self.groupBox_PrereductionMode)
        self.comboBox_detector.setGeometry(QtCore.QRect(200, 190, 118, 21))
        self.comboBox_detector.setObjectName(_fromUtf8("comboBox_detector"))
        self.comboBox_detector.addItem(_fromUtf8(""))
        self.comboBox_detector.addItem(_fromUtf8(""))
        self.comboBox_detector.addItem(_fromUtf8(""))
        self.comboBox_detector.addItem(_fromUtf8(""))
        self.comboBox_detector.addItem(_fromUtf8(""))
        self.textLabel3_3 = QtGui.QLabel(self.groupBox_PrereductionMode)
        self.textLabel3_3.setGeometry(QtCore.QRect(200, 170, 151, 16))
        self.textLabel3_3.setWordWrap(False)
        self.textLabel3_3.setObjectName(_fromUtf8("textLabel3_3"))
        self.comboBox_AstromEngine = QtGui.QComboBox(self.groupBox_PrereductionMode)
        self.comboBox_AstromEngine.setGeometry(QtCore.QRect(380, 190, 118, 21))
        self.comboBox_AstromEngine.setObjectName(_fromUtf8("comboBox_AstromEngine"))
        self.comboBox_AstromEngine.addItem(_fromUtf8(""))
        self.comboBox_AstromEngine.addItem(_fromUtf8(""))
        self.textLabel3_4 = QtGui.QLabel(self.groupBox_PrereductionMode)
        self.textLabel3_4.setGeometry(QtCore.QRect(380, 170, 161, 16))
        self.textLabel3_4.setWordWrap(False)
        self.textLabel3_4.setObjectName(_fromUtf8("textLabel3_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.TabPage)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 150, 271, 91))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.comboBox_show_imgs = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_show_imgs.setGeometry(QtCore.QRect(30, 30, 211, 22))
        self.comboBox_show_imgs.setObjectName(_fromUtf8("comboBox_show_imgs"))
        self.comboBox_show_imgs.addItem(_fromUtf8(""))
        self.comboBox_show_imgs.addItem(_fromUtf8(""))
        self.comboBox_show_imgs.addItem(_fromUtf8(""))
        self.comboBox_show_imgs.addItem(_fromUtf8(""))
        self.tabWidget3.addTab(self.TabPage, _fromUtf8(""))
        self.tab1 = QtGui.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.textLabel3_2 = QtGui.QLabel(self.tab1)
        self.textLabel3_2.setGeometry(QtCore.QRect(661, 114, 51, 22))
        self.textLabel3_2.setWordWrap(False)
        self.textLabel3_2.setObjectName(_fromUtf8("textLabel3_2"))
        self.lineEdit_masterFlat_Filter = QtGui.QLineEdit(self.tab1)
        self.lineEdit_masterFlat_Filter.setGeometry(QtCore.QRect(583, 114, 70, 21))
        self.lineEdit_masterFlat_Filter.setText(_fromUtf8(""))
        self.lineEdit_masterFlat_Filter.setReadOnly(True)
        self.lineEdit_masterFlat_Filter.setObjectName(_fromUtf8("lineEdit_masterFlat_Filter"))
        self.pushButton_loadLastCalibs = QtGui.QPushButton(self.tab1)
        self.pushButton_loadLastCalibs.setEnabled(True)
        self.pushButton_loadLastCalibs.setGeometry(QtCore.QRect(34, 36, 120, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 152, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 126, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 67, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 178, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 152, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 126, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 67, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 178, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 152, 49))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 126, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 67, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 50, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 101, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_loadLastCalibs.setPalette(palette)
        self.pushButton_loadLastCalibs.setStatusTip(_fromUtf8(""))
        self.pushButton_loadLastCalibs.setObjectName(_fromUtf8("pushButton_loadLastCalibs"))
        self.pushButton_test1 = QtGui.QPushButton(self.tab1)
        self.pushButton_test1.setEnabled(False)
        self.pushButton_test1.setGeometry(QtCore.QRect(800, 40, 108, 23))
        self.pushButton_test1.setObjectName(_fromUtf8("pushButton_test1"))
        self.checkBox_use_defCalibs = QtGui.QCheckBox(self.tab1)
        self.checkBox_use_defCalibs.setGeometry(QtCore.QRect(172, 43, 121, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_use_defCalibs.setFont(font)
        self.checkBox_use_defCalibs.setObjectName(_fromUtf8("checkBox_use_defCalibs"))
        self.lineEdit_masterDark_texp = QtGui.QLineEdit(self.tab1)
        self.lineEdit_masterDark_texp.setGeometry(QtCore.QRect(584, 84, 70, 21))
        self.lineEdit_masterDark_texp.setText(_fromUtf8(""))
        self.lineEdit_masterDark_texp.setReadOnly(True)
        self.lineEdit_masterDark_texp.setObjectName(_fromUtf8("lineEdit_masterDark_texp"))
        self.textLabel3_5 = QtGui.QLabel(self.tab1)
        self.textLabel3_5.setGeometry(QtCore.QRect(661, 86, 61, 22))
        self.textLabel3_5.setWordWrap(False)
        self.textLabel3_5.setObjectName(_fromUtf8("textLabel3_5"))
        self.lineEdit_readout_mode = QtGui.QLineEdit(self.tab1)
        self.lineEdit_readout_mode.setGeometry(QtCore.QRect(583, 174, 70, 21))
        self.lineEdit_readout_mode.setText(_fromUtf8(""))
        self.lineEdit_readout_mode.setReadOnly(True)
        self.lineEdit_readout_mode.setObjectName(_fromUtf8("lineEdit_readout_mode"))
        self.textLabel3_6 = QtGui.QLabel(self.tab1)
        self.textLabel3_6.setGeometry(QtCore.QRect(661, 174, 111, 22))
        self.textLabel3_6.setWordWrap(False)
        self.textLabel3_6.setObjectName(_fromUtf8("textLabel3_6"))
        self.layoutWidget2 = QtGui.QWidget(self.tab1)
        self.layoutWidget2.setGeometry(QtCore.QRect(173, 81, 401, 121))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lineEdit_masterDark = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterDark.setEnabled(False)
        self.lineEdit_masterDark.setReadOnly(True)
        self.lineEdit_masterDark.setObjectName(_fromUtf8("lineEdit_masterDark"))
        self.verticalLayout_5.addWidget(self.lineEdit_masterDark)
        self.lineEdit_masterFlat = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterFlat.setEnabled(False)
        self.lineEdit_masterFlat.setReadOnly(True)
        self.lineEdit_masterFlat.setObjectName(_fromUtf8("lineEdit_masterFlat"))
        self.verticalLayout_5.addWidget(self.lineEdit_masterFlat)
        self.lineEdit_masterMask = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterMask.setEnabled(False)
        self.lineEdit_masterMask.setReadOnly(True)
        self.lineEdit_masterMask.setObjectName(_fromUtf8("lineEdit_masterMask"))
        self.verticalLayout_5.addWidget(self.lineEdit_masterMask)
        self.lineEdit_masterNLC = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_masterNLC.setEnabled(False)
        self.lineEdit_masterNLC.setReadOnly(True)
        self.lineEdit_masterNLC.setObjectName(_fromUtf8("lineEdit_masterNLC"))
        self.verticalLayout_5.addWidget(self.lineEdit_masterNLC)
        self.layoutWidget3 = QtGui.QWidget(self.tab1)
        self.layoutWidget3.setGeometry(QtCore.QRect(23, 79, 141, 125))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pushButton_master_dark = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_master_dark.setEnabled(True)
        self.pushButton_master_dark.setObjectName(_fromUtf8("pushButton_master_dark"))
        self.verticalLayout_6.addWidget(self.pushButton_master_dark)
        self.pushButton_master_flat = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_master_flat.setEnabled(True)
        self.pushButton_master_flat.setObjectName(_fromUtf8("pushButton_master_flat"))
        self.verticalLayout_6.addWidget(self.pushButton_master_flat)
        self.pushButton_master_mask = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_master_mask.setEnabled(True)
        self.pushButton_master_mask.setObjectName(_fromUtf8("pushButton_master_mask"))
        self.verticalLayout_6.addWidget(self.pushButton_master_mask)
        self.pushButton_master_nlc = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_master_nlc.setEnabled(True)
        self.pushButton_master_nlc.setObjectName(_fromUtf8("pushButton_master_nlc"))
        self.verticalLayout_6.addWidget(self.pushButton_master_nlc)
        self.comboBox_bpm_action = QtGui.QComboBox(self.tab1)
        self.comboBox_bpm_action.setGeometry(QtCore.QRect(586, 145, 90, 21))
        self.comboBox_bpm_action.setObjectName(_fromUtf8("comboBox_bpm_action"))
        self.comboBox_bpm_action.addItem(_fromUtf8(""))
        self.comboBox_bpm_action.addItem(_fromUtf8(""))
        self.comboBox_bpm_action.addItem(_fromUtf8(""))
        self.textLabel3_7 = QtGui.QLabel(self.tab1)
        self.textLabel3_7.setGeometry(QtCore.QRect(684, 145, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textLabel3_7.setFont(font)
        self.textLabel3_7.setWordWrap(False)
        self.textLabel3_7.setObjectName(_fromUtf8("textLabel3_7"))
        self.tabWidget3.addTab(self.tab1, _fromUtf8(""))
        self.TabPage1 = QtGui.QWidget()
        self.TabPage1.setObjectName(_fromUtf8("TabPage1"))
        self.textLabel1_7 = QtGui.QLabel(self.TabPage1)
        self.textLabel1_7.setGeometry(QtCore.QRect(11, 8, 100, 20))
        self.textLabel1_7.setWordWrap(False)
        self.textLabel1_7.setObjectName(_fromUtf8("textLabel1_7"))
        self.textEdit_log_2 = QtGui.QTextEdit(self.TabPage1)
        self.textEdit_log_2.setGeometry(QtCore.QRect(10, 30, 901, 391))
        self.textEdit_log_2.setObjectName(_fromUtf8("textEdit_log_2"))
        self.tabWidget3.addTab(self.TabPage1, _fromUtf8(""))
        self.textEdit_log = QtGui.QTextEdit(self.widget)
        self.textEdit_log.setGeometry(QtCore.QRect(5, 480, 941, 181))
        self.textEdit_log.setObjectName(_fromUtf8("textEdit_log"))
        panicQL.setCentralWidget(self.widget)
        self.toolBar = QtGui.QToolBar(panicQL)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        panicQL.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.Toolbar = QtGui.QToolBar(panicQL)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Toolbar.sizePolicy().hasHeightForWidth())
        self.Toolbar.setSizePolicy(sizePolicy)
        self.Toolbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Toolbar.setAllowedAreas(QtCore.Qt.RightToolBarArea)
        self.Toolbar.setObjectName(_fromUtf8("Toolbar"))
        panicQL.addToolBar(QtCore.Qt.TopToolBarArea, self.Toolbar)
        self.MenuBar = QtGui.QMenuBar(panicQL)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 961, 24))
        self.MenuBar.setObjectName(_fromUtf8("MenuBar"))
        self.fileMenu = QtGui.QMenu(self.MenuBar)
        self.fileMenu.setObjectName(_fromUtf8("fileMenu"))
        self.viewMenu = QtGui.QMenu(self.MenuBar)
        self.viewMenu.setObjectName(_fromUtf8("viewMenu"))
        self.Settings = QtGui.QMenu(self.MenuBar)
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.Calibrations = QtGui.QMenu(self.MenuBar)
        self.Calibrations.setObjectName(_fromUtf8("Calibrations"))
        self.Tools = QtGui.QMenu(self.MenuBar)
        self.Tools.setObjectName(_fromUtf8("Tools"))
        self.helpMenu = QtGui.QMenu(self.MenuBar)
        self.helpMenu.setObjectName(_fromUtf8("helpMenu"))
        panicQL.setMenuBar(self.MenuBar)
        self.fileOpenAction = QtGui.QAction(panicQL)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/archive-insert.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileOpenAction.setIcon(icon1)
        self.fileOpenAction.setProperty("name", _fromUtf8("fileOpenAction"))
        self.fileOpenAction.setObjectName(_fromUtf8("fileOpenAction"))
        self.fileDirAction = QtGui.QAction(panicQL)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/archive-insert-directory.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileDirAction.setIcon(icon2)
        self.fileDirAction.setProperty("name", _fromUtf8("fileDirAction"))
        self.fileDirAction.setObjectName(_fromUtf8("fileDirAction"))
        self.fileShow = QtGui.QAction(panicQL)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../../home/staff1/papi/QL4/images/ds9.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileShow.setIcon(icon3)
        self.fileShow.setProperty("name", _fromUtf8("fileShow"))
        self.fileShow.setObjectName(_fromUtf8("fileShow"))
        self.fileSaveAsAction = QtGui.QAction(panicQL)
        self.fileSaveAsAction.setShortcut(_fromUtf8(""))
        self.fileSaveAsAction.setProperty("name", _fromUtf8("fileSaveAsAction"))
        self.fileSaveAsAction.setObjectName(_fromUtf8("fileSaveAsAction"))
        self.filePrintAction = QtGui.QAction(panicQL)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../.designer/backup/image4")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filePrintAction.setIcon(icon4)
        self.filePrintAction.setProperty("name", _fromUtf8("filePrintAction"))
        self.filePrintAction.setObjectName(_fromUtf8("filePrintAction"))
        self.fileExitAction = QtGui.QAction(panicQL)
        self.fileExitAction.setShortcut(_fromUtf8(""))
        self.fileExitAction.setProperty("name", _fromUtf8("fileExitAction"))
        self.fileExitAction.setObjectName(_fromUtf8("fileExitAction"))
        self.editCutAction = QtGui.QAction(panicQL)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../.designer/backup/image7")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editCutAction.setIcon(icon5)
        self.editCutAction.setProperty("name", _fromUtf8("editCutAction"))
        self.editCutAction.setObjectName(_fromUtf8("editCutAction"))
        self.viewHeaderAction = QtGui.QAction(panicQL)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../.designer/backup/image8")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewHeaderAction.setIcon(icon6)
        self.viewHeaderAction.setProperty("name", _fromUtf8("editCopyAction"))
        self.viewHeaderAction.setObjectName(_fromUtf8("viewHeaderAction"))
        self.viewImageAction = QtGui.QAction(panicQL)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../.designer/backup/image9")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewImageAction.setIcon(icon7)
        self.viewImageAction.setProperty("name", _fromUtf8("editPasteAction"))
        self.viewImageAction.setObjectName(_fromUtf8("viewImageAction"))
        self.editFindAction = QtGui.QAction(panicQL)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../.designer/backup/image10")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editFindAction.setIcon(icon8)
        self.editFindAction.setProperty("name", _fromUtf8("editFindAction"))
        self.editFindAction.setObjectName(_fromUtf8("editFindAction"))
        self.helpIndexAction = QtGui.QAction(panicQL)
        self.helpIndexAction.setProperty("name", _fromUtf8("helpIndexAction"))
        self.helpIndexAction.setObjectName(_fromUtf8("helpIndexAction"))
        self.new_menudAction = QtGui.QAction(panicQL)
        self.new_menudAction.setProperty("name", _fromUtf8("new_menudAction"))
        self.new_menudAction.setObjectName(_fromUtf8("new_menudAction"))
        self.calibrationsMaster_FlatAction = QtGui.QAction(panicQL)
        self.calibrationsMaster_FlatAction.setProperty("name", _fromUtf8("calibrationsMaster_FlatAction"))
        self.calibrationsMaster_FlatAction.setObjectName(_fromUtf8("calibrationsMaster_FlatAction"))
        self.calibrationsMaster_Sky_FlatAction = QtGui.QAction(panicQL)
        self.calibrationsMaster_Sky_FlatAction.setProperty("name", _fromUtf8("calibrationsMaster_Sky_FlatAction"))
        self.calibrationsMaster_Sky_FlatAction.setObjectName(_fromUtf8("calibrationsMaster_Sky_FlatAction"))
        self.toolsIRAF_consoleAction = QtGui.QAction(panicQL)
        self.toolsIRAF_consoleAction.setProperty("name", _fromUtf8("toolsIRAF_consoleAction"))
        self.toolsIRAF_consoleAction.setObjectName(_fromUtf8("toolsIRAF_consoleAction"))
        self.toolsDS9_displayAction = QtGui.QAction(panicQL)
        self.toolsDS9_displayAction.setProperty("name", _fromUtf8("toolsDS9_displayAction"))
        self.toolsDS9_displayAction.setObjectName(_fromUtf8("toolsDS9_displayAction"))
        self.toolsAladinAction = QtGui.QAction(panicQL)
        self.toolsAladinAction.setProperty("name", _fromUtf8("toolsAladinAction"))
        self.toolsAladinAction.setObjectName(_fromUtf8("toolsAladinAction"))
        self.fileSearchAction = QtGui.QAction(panicQL)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/edit-find.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileSearchAction.setIcon(icon9)
        self.fileSearchAction.setProperty("name", _fromUtf8("fileSearchAction"))
        self.fileSearchAction.setObjectName(_fromUtf8("fileSearchAction"))
        self.quitAction = QtGui.QAction(panicQL)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/actions/system-shutdown.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitAction.setIcon(icon10)
        self.quitAction.setProperty("name", _fromUtf8("quitAction"))
        self.quitAction.setObjectName(_fromUtf8("quitAction"))
        self.irafConsoleAction = QtGui.QAction(panicQL)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../../../usr/share/icons/default.kde4/32x32/apps/package_system_shell.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.irafConsoleAction.setIcon(icon11)
        self.irafConsoleAction.setProperty("name", _fromUtf8("irafConsoleAction"))
        self.irafConsoleAction.setObjectName(_fromUtf8("irafConsoleAction"))
        self.actionAbout = QtGui.QAction(panicQL)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionAladin = QtGui.QAction(panicQL)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("images/aladin_large.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAladin.setIcon(icon12)
        self.actionAladin.setObjectName(_fromUtf8("actionAladin"))
        self.toolBar.addAction(self.fileOpenAction)
        self.toolBar.addAction(self.fileDirAction)
        self.toolBar.addAction(self.fileShow)
        self.toolBar.addAction(self.fileSearchAction)
        self.toolBar.addAction(self.actionAladin)
        self.toolBar.addAction(self.irafConsoleAction)
        self.Toolbar.addAction(self.quitAction)
        self.fileMenu.addAction(self.fileOpenAction)
        self.fileMenu.addAction(self.fileDirAction)
        self.fileMenu.addAction(self.fileShow)
        self.fileMenu.addAction(self.fileSaveAsAction)
        self.fileMenu.addSeparator()
        self.fileMenu.addSeparator()
        self.fileMenu.addAction(self.fileExitAction)
        self.viewMenu.addAction(self.viewHeaderAction)
        self.viewMenu.addAction(self.viewImageAction)
        self.viewMenu.addSeparator()
        self.viewMenu.addAction(self.editFindAction)
        self.Calibrations.addAction(self.new_menudAction)
        self.Calibrations.addAction(self.calibrationsMaster_FlatAction)
        self.Calibrations.addAction(self.calibrationsMaster_Sky_FlatAction)
        self.Tools.addAction(self.toolsIRAF_consoleAction)
        self.Tools.addAction(self.toolsDS9_displayAction)
        self.Tools.addAction(self.toolsAladinAction)
        self.helpMenu.addAction(self.helpIndexAction)
        self.helpMenu.addSeparator()
        self.helpMenu.addAction(self.actionAbout)
        self.MenuBar.addAction(self.fileMenu.menuAction())
        self.MenuBar.addAction(self.viewMenu.menuAction())
        self.MenuBar.addAction(self.Settings.menuAction())
        self.MenuBar.addAction(self.Calibrations.menuAction())
        self.MenuBar.addAction(self.Tools.menuAction())
        self.MenuBar.addSeparator()
        self.MenuBar.addAction(self.helpMenu.menuAction())

        self.retranslateUi(panicQL)
        self.tabWidget3.setCurrentIndex(0)
        self.comboBox_pre_skyWindow.setCurrentIndex(3)
        self.comboBox_detector.setCurrentIndex(0)
        self.comboBox_AstromEngine.setCurrentIndex(0)
        QtCore.QObject.connect(self.viewHeaderAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editCopy)
        QtCore.QObject.connect(self.editCutAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editCut)
        QtCore.QObject.connect(self.editFindAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editFind)
        QtCore.QObject.connect(self.viewImageAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.editPaste)
        QtCore.QObject.connect(self.fileDirAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileOpen)
        QtCore.QObject.connect(self.fileExitAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileExit)
        QtCore.QObject.connect(self.fileOpenAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.add_slot)
        QtCore.QObject.connect(self.filePrintAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.filePrint)
        QtCore.QObject.connect(self.fileSaveAsAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileSaveAs)
        QtCore.QObject.connect(self.fileShow, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.display_slot)
        QtCore.QObject.connect(self.helpIndexAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.helpIndex)
        QtCore.QObject.connect(self.irafConsoleAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.iraf_console_slot)
        QtCore.QObject.connect(self.quitAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.fileExit)
        QtCore.QObject.connect(self.toolsAladinAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.start_aladin_slot)
        QtCore.QObject.connect(self.toolsDS9_displayAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.start_ds9_slot)
        QtCore.QObject.connect(self.toolsIRAF_consoleAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.iraf_console_slot)
        QtCore.QObject.connect(self.helpIndexAction, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.helpIndex)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.helpAbout)
        QtCore.QObject.connect(self.actionAladin, QtCore.SIGNAL(_fromUtf8("activated()")), panicQL.start_aladin_slot)
        QtCore.QObject.connect(self.checkBox_autocheck, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.autocheck_slot)
        QtCore.QObject.connect(self.checkBox_outDir_autocheck, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.checkOutDir_slot)
        QtCore.QObject.connect(self.comboBox_classFilter, QtCore.SIGNAL(_fromUtf8("activated(QString)")), panicQL.slot_classFilter)
        QtCore.QObject.connect(self.pushButton_add, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.add_slot)
        QtCore.QObject.connect(self.pushButton_clear, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.clear_mainlist_slot)
        QtCore.QObject.connect(self.pushButton_loadLastCalibs, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_updateCalibs_slot)
        QtCore.QObject.connect(self.pushButton_master_dark, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_masterDark_slot)
        QtCore.QObject.connect(self.pushButton_master_mask, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_masterMask_slot)
        QtCore.QObject.connect(self.pushButton_file_filter, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.filename_filter_slot)
        QtCore.QObject.connect(self.pushButton_dataSourceD, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setDataSourceDir_slot)
        QtCore.QObject.connect(self.pushButton_remove, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.del_slot)
        QtCore.QObject.connect(self.pushButton_outputD, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setOutputDir_slot)
        QtCore.QObject.connect(self.pushButton_master_flat, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_masterFlat_slot)
        QtCore.QObject.connect(self.pushButton_start_proc, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_start_stop_slot)
        QtCore.QObject.connect(self.pushButton_createCalibs, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.createCalibs_slot)
        QtCore.QObject.connect(self.pushButton_subtract_last2, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_subtract_last2_slot)
        QtCore.QObject.connect(self.checkBox_pre_appSF, QtCore.SIGNAL(_fromUtf8("clicked()")), self.checkBox_pre_subDark_FF.toggle)
        QtCore.QObject.connect(self.checkBox_pre_subDark_FF, QtCore.SIGNAL(_fromUtf8("clicked()")), self.checkBox_pre_appSF.toggle)
        QtCore.QObject.connect(self.pushButton_tempD, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setTempDir_slot)
        QtCore.QObject.connect(self.checkBox_geirsFile, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setGEIRS_Input_slot)
        QtCore.QObject.connect(self.pushButton_master_nlc, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.pushB_sel_masterNLC_slot)
        QtCore.QObject.connect(self.checkBox_currentNight, QtCore.SIGNAL(_fromUtf8("clicked()")), panicQL.setCurrentNight_Input_slot)
        QtCore.QMetaObject.connectSlotsByName(panicQL)

    def retranslateUi(self, panicQL):
        panicQL.setWindowTitle(_translate("panicQL", "PANIC QuickLook", None))
        self.textLabel1_7_2.setText(_translate("panicQL", "<font color=\"#1759ff\">Event log (Time UTC)</font>", None))
        self.checkBox_autocheck.setToolTip(_translate("panicQL", "Autocheck for new incoming images", None))
        self.checkBox_outDir_autocheck.setToolTip(_translate("panicQL", "Autocheck for new incoming images to output dir", None))
        self.textLabel1_3.setText(_translate("panicQL", "Check", None))
        self.pushButton_remove.setToolTip(_translate("panicQL", "Remove data file from the list view, but keeping on disk", "Remove data file from the list view, but keeping on disk"))
        self.pushButton_remove.setText(_translate("panicQL", "Remove", None))
        self.pushButton_add.setText(_translate("panicQL", "Add...", None))
        self.pushButton_clear.setToolTip(_translate("panicQL", "Clear list view panel, but not files on disk", None))
        self.pushButton_clear.setText(_translate("panicQL", "Clear All", None))
        self.textLabel2_3.setText(_translate("panicQL", "Last file received:", None))
        self.pushButton_dataSourceD.setToolTip(_translate("panicQL", "Select a directory or log file for received files location", None))
        self.pushButton_dataSourceD.setText(_translate("panicQL", "Input Dir", None))
        self.lineEdit_outputD.setToolTip(_translate("panicQL", "Processed files location", None))
        self.pushButton_outputD.setToolTip(_translate("panicQL", "Browse the output processed files location", None))
        self.pushButton_outputD.setText(_translate("panicQL", "Output Dir", None))
        self.pushButton_file_filter.setText(_translate("panicQL", "Set Filename Filter", None))
        self.pushButton_createCalibs.setText(_translate("panicQL", "Create Calibrations", None))
        self.textLabel4_2_3.setText(_translate("panicQL", "Data List View", None))
        self.textLabel4_2.setText(_translate("panicQL", "List View Filter", None))
        self.comboBox_classFilter.setToolTip(_translate("panicQL", "Filter data sources list using its class/type", None))
        self.comboBox_classFilter.setItemText(0, _translate("panicQL", "INPUTS", None))
        self.comboBox_classFilter.setItemText(1, _translate("panicQL", "OUTS", None))
        self.comboBox_classFilter.setItemText(2, _translate("panicQL", "DARK", None))
        self.comboBox_classFilter.setItemText(3, _translate("panicQL", "DOME_FLAT", None))
        self.comboBox_classFilter.setItemText(4, _translate("panicQL", "SKY_FLAT", None))
        self.comboBox_classFilter.setItemText(5, _translate("panicQL", "SCIENCE", None))
        self.comboBox_classFilter.setItemText(6, _translate("panicQL", "REDUCED", None))
        self.comboBox_classFilter.setItemText(7, _translate("panicQL", "GROUP", None))
        self.comboBox_classFilter.setItemText(8, _translate("panicQL", "ALL", None))
        self.comboBox_QL_Mode.setToolTip(_translate("panicQL", "Filter data sources list using its class/type", None))
        self.comboBox_QL_Mode.setItemText(0, _translate("panicQL", "None", None))
        self.comboBox_QL_Mode.setItemText(1, _translate("panicQL", "Lazy", None))
        self.comboBox_QL_Mode.setItemText(2, _translate("panicQL", "Pre-reduction", None))
        self.comboBox_QL_Mode.setItemText(3, _translate("panicQL", "Quick-LEMON", None))
        self.comboBox_QL_Mode.setItemText(4, _translate("panicQL", "Full-LEMON", None))
        self.comboBox_QL_Mode.setItemText(5, _translate("panicQL", "Full-Reduction", None))
        self.textLabel4_2_2.setText(_translate("panicQL", "QL Mode", None))
        self.pushButton_start_proc.setText(_translate("panicQL", "START processing", None))
        self.pushButton_subtract_last2.setText(_translate("panicQL", "Subtract-Last2", None))
        self.lineEdit_sourceD.setToolTip(_translate("panicQL", "Input raw files location", None))
        self.lineEdit_filename_filter.setToolTip(_translate("panicQL", "Input data file extension", None))
        self.lineEdit_filename_filter.setText(_translate("panicQL", "*.fits", None))
        self.listView_dataS.setSortingEnabled(True)
        self.listView_dataS.headerItem().setText(0, _translate("panicQL", "Filename", None))
        self.listView_dataS.headerItem().setText(1, _translate("panicQL", "ImageType", None))
        self.listView_dataS.headerItem().setText(2, _translate("panicQL", "Filter", None))
        self.listView_dataS.headerItem().setText(3, _translate("panicQL", "ExpT", None))
        self.listView_dataS.headerItem().setText(4, _translate("panicQL", "Date-Obs", None))
        self.listView_dataS.headerItem().setText(5, _translate("panicQL", "Object", None))
        self.listView_dataS.headerItem().setText(6, _translate("panicQL", "RA", None))
        self.listView_dataS.headerItem().setText(7, _translate("panicQL", "Dec", None))
        self.lineEdit_queue_size.setToolTip(_translate("panicQL", "Number of task currently queued", None))
        self.lineEdit_queue_size.setText(_translate("panicQL", "0", None))
        self.label.setText(_translate("panicQL", "#Tasks in the queue", None))
        self.checkBox_geirsFile.setToolTip(_translate("panicQL", "Auto-select GEIRS log file ~/tmp/fitsGeirsWritten", None))
        self.textLabel1_5.setStatusTip(_translate("panicQL", "Read input files from GEIRS log file ~/tmp/fitsGeirsWritten", None))
        self.textLabel1_5.setText(_translate("panicQL", "Use GEIRS file", None))
        self.checkBox_currentNight.setToolTip(_translate("panicQL", "Auto-select current night directory", None))
        self.textLabel1_6.setStatusTip(_translate("panicQL", "Read input files from GEIRS log file ~/tmp/fitsGeirsWritten", None))
        self.textLabel1_6.setText(_translate("panicQL", "Current night", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab), _translate("panicQL", "Main", None))
        self.groupBox.setTitle(_translate("panicQL", "Common Settings", None))
        self.checkBox.setText(_translate("panicQL", "Check header", None))
        self.checkBox7_2_2_2.setText(_translate("panicQL", "Create Log file", None))
        self.pushButton_tempD.setToolTip(_translate("panicQL", "Browse the temporal file location", None))
        self.pushButton_tempD.setText(_translate("panicQL", "Temporary Dir", None))
        self.lineEdit_tempD.setToolTip(_translate("panicQL", "Temporal files location", None))
        self.groupBox_2.setTitle(_translate("panicQL", "Data Grouping", None))
        self.textLabel5.setText(_translate("panicQL", "arcsecs", None))
        self.textLabel5_2.setText(_translate("panicQL", "secs", None))
        self.checkBox_data_grouping_OT.setText(_translate("panicQL", "OT Keywords", None))
        self.textLabel5_3.setText(_translate("panicQL", "files", None))
        self.textLabel4_3.setText(_translate("panicQL", "RA,Dec offsets", None))
        self.textLabel4_3_2.setText(_translate("panicQL", "Time offsets", None))
        self.textLabel4_3_3.setText(_translate("panicQL", "Max. num.files", None))
        self.lineEdit_ra_dec_near_offset.setInputMask(_translate("panicQL", "#####; ", None))
        self.lineEdit_ra_dec_near_offset.setText(_translate("panicQL", "600", None))
        self.lineEdit_time_near_offset.setInputMask(_translate("panicQL", "#####; ", None))
        self.lineEdit_time_near_offset.setText(_translate("panicQL", "900", None))
        self.lineEdit_max_num_files.setInputMask(_translate("panicQL", "####; ", None))
        self.lineEdit_max_num_files.setText(_translate("panicQL", "50", None))
        self.groupBox_3.setTitle(_translate("panicQL", "Astrometry", None))
        self.comboBox_AstromCatalog.setItemText(0, _translate("panicQL", "2MASS", None))
        self.comboBox_AstromCatalog.setItemText(1, _translate("panicQL", "USNO-B1", None))
        self.comboBox_AstromCatalog.setItemText(2, _translate("panicQL", "GSC 2.2", None))
        self.comboBox_AstromCatalog.setItemText(3, _translate("panicQL", "SDSS-R5", None))
        self.comboBox_AstromCatalog.setItemText(4, _translate("panicQL", "UCAC-2", None))
        self.comboBox_AstromCatalog.setItemText(5, _translate("panicQL", "FILE", None))
        self.textLabel1_2.setText(_translate("panicQL", "Catalog", None))
        self.groupBox_LazyMode.setTitle(_translate("panicQL", "Lazy Mode", None))
        self.checkBox_subDark_FF_BPM.setToolTip(_translate("panicQL", "Substract Dark, apply Flat-Field and grab BPM", None))
        self.checkBox_subDark_FF_BPM.setText(_translate("panicQL", "Apply DARK + FLAT + BPM", None))
        self.checkBox_subLastFrame.setStatusTip(_translate("panicQL", "Subtract last science frame for sky subtraction", None))
        self.checkBox_subLastFrame.setText(_translate("panicQL", "Subtract Last Frame (science)", None))
        self.checkBox_subSky.setStatusTip(_translate("panicQL", "Subtract the sky computed from last sky sci frames", None))
        self.checkBox_subSky.setText(_translate("panicQL", "Subtract Nearest Sky", None))
        self.groupBox_PrereductionMode.setTitle(_translate("panicQL", "Pre-Reduction Mode", None))
        self.comboBox_pre_skyWindow.setItemText(0, _translate("panicQL", "1-Current frame", None))
        self.comboBox_pre_skyWindow.setItemText(1, _translate("panicQL", "2-frames", None))
        self.comboBox_pre_skyWindow.setItemText(2, _translate("panicQL", "3-frames", None))
        self.comboBox_pre_skyWindow.setItemText(3, _translate("panicQL", "4-frames", None))
        self.comboBox_pre_skyWindow.setItemText(4, _translate("panicQL", "5-frames", None))
        self.checkBox_pre_QM.setText(_translate("panicQL", "Quality measurements  (background, psf, ....)", None))
        self.textLabel3.setText(_translate("panicQL", "# sky nearest frames", None))
        self.checkBox_pre_MA.setText(_translate("panicQL", "Make Astrometry", None))
        self.checkBox_pre_appBPM.setText(_translate("panicQL", "Apply BPM", None))
        self.checkBox_pre_subDark_FF.setText(_translate("panicQL", "Apply DARK/FLAT", None))
        self.checkBox_pre_appSF.setText(_translate("panicQL", "Apply SuperFlat", None))
        self.checkBox_pre_BS.setText(_translate("panicQL", "Build stacked image", None))
        self.checkBox_pre_appNLC.setText(_translate("panicQL", "Correct for non-linearity", None))
        self.comboBox_detector.setItemText(0, _translate("panicQL", "All", None))
        self.comboBox_detector.setItemText(1, _translate("panicQL", "SG1", None))
        self.comboBox_detector.setItemText(2, _translate("panicQL", "SG2", None))
        self.comboBox_detector.setItemText(3, _translate("panicQL", "SG3", None))
        self.comboBox_detector.setItemText(4, _translate("panicQL", "SG4", None))
        self.textLabel3_3.setText(_translate("panicQL", "Detector to reduce", None))
        self.comboBox_AstromEngine.setItemText(0, _translate("panicQL", "AstrometryNet", None))
        self.comboBox_AstromEngine.setItemText(1, _translate("panicQL", "SCAMP", None))
        self.textLabel3_4.setText(_translate("panicQL", "Astrometric Engine", None))
        self.groupBox_4.setTitle(_translate("panicQL", "Display", None))
        self.comboBox_show_imgs.setItemText(0, _translate("panicQL", "None", None))
        self.comboBox_show_imgs.setItemText(1, _translate("panicQL", "Only new files in \'Input Dir\'", None))
        self.comboBox_show_imgs.setItemText(2, _translate("panicQL", "Only results", None))
        self.comboBox_show_imgs.setItemText(3, _translate("panicQL", "All files", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.TabPage), _translate("panicQL", "Setup", None))
        self.textLabel3_2.setText(_translate("panicQL", "<b>Filter</b>", None))
        self.pushButton_loadLastCalibs.setToolTip(_translate("panicQL", "Load last calibration files received", None))
        self.pushButton_loadLastCalibs.setWhatsThis(_translate("panicQL", "Load last calibration files received", None))
        self.pushButton_loadLastCalibs.setText(_translate("panicQL", "Load last", None))
        self.pushButton_test1.setText(_translate("panicQL", "Test1", None))
        self.checkBox_use_defCalibs.setToolTip(_translate("panicQL", "Use next files as default calibration files (not recommended!)", None))
        self.checkBox_use_defCalibs.setText(_translate("panicQL", "Use as defaults", None))
        self.textLabel3_5.setText(_translate("panicQL", "<html><head/><body><p><span style=\" font-weight:600;\">T.Exp.(s)</span></p><p><br/></p></body></html>", None))
        self.textLabel3_6.setText(_translate("panicQL", "<html><head/><body><p><span style=\" font-weight:600;\">Readout-Mode</span></p></body></html>", None))
        self.pushButton_master_dark.setText(_translate("panicQL", "Master Dark...", None))
        self.pushButton_master_flat.setText(_translate("panicQL", "Master Flat...", None))
        self.pushButton_master_mask.setText(_translate("panicQL", "Master BPM...", None))
        self.pushButton_master_nlc.setText(_translate("panicQL", "Master NLC...", None))
        self.comboBox_bpm_action.setItemText(0, _translate("panicQL", "None", None))
        self.comboBox_bpm_action.setItemText(1, _translate("panicQL", "Set NaNs", None))
        self.comboBox_bpm_action.setItemText(2, _translate("panicQL", "Fix", None))
        self.textLabel3_7.setText(_translate("panicQL", "<html><head/><body><p>Action</p></body></html>", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.tab1), _translate("panicQL", "Calibrations", None))
        self.textLabel1_7.setText(_translate("panicQL", "<font color=\"#1759ff\">Times in UTC</font>", None))
        self.tabWidget3.setTabText(self.tabWidget3.indexOf(self.TabPage1), _translate("panicQL", "Logs", None))
        self.toolBar.setProperty("label", _translate("panicQL", "Tools", None))
        self.Toolbar.setProperty("label", _translate("panicQL", "Toolbar", None))
        self.fileMenu.setTitle(_translate("panicQL", "&File", None))
        self.viewMenu.setTitle(_translate("panicQL", "View", None))
        self.Settings.setTitle(_translate("panicQL", "Settings", None))
        self.Calibrations.setTitle(_translate("panicQL", "Calibrations", None))
        self.Tools.setTitle(_translate("panicQL", "Tools", None))
        self.helpMenu.setTitle(_translate("panicQL", "&Help", None))
        self.fileOpenAction.setText(_translate("panicQL", "&Open", None))
        self.fileOpenAction.setIconText(_translate("panicQL", "Open", None))
        self.fileOpenAction.setToolTip(_translate("panicQL", "Add a new file to \'Data List View\'", None))
        self.fileOpenAction.setShortcut(_translate("panicQL", "Ctrl+O", None))
        self.fileDirAction.setText(_translate("panicQL", "&Open...", None))
        self.fileDirAction.setIconText(_translate("panicQL", "Open", None))
        self.fileDirAction.setToolTip(_translate("panicQL", "Change data source directory", None))
        self.fileDirAction.setShortcut(_translate("panicQL", "Ctrl+I", None))
        self.fileShow.setText(_translate("panicQL", "&Show", None))
        self.fileShow.setIconText(_translate("panicQL", "Show", None))
        self.fileShow.setToolTip(_translate("panicQL", "Show image", None))
        self.fileShow.setShortcut(_translate("panicQL", "Ctrl+D", None))
        self.fileSaveAsAction.setText(_translate("panicQL", "Save &As...", None))
        self.fileSaveAsAction.setIconText(_translate("panicQL", "Save As", None))
        self.filePrintAction.setText(_translate("panicQL", "&Print...", None))
        self.filePrintAction.setIconText(_translate("panicQL", "Print", None))
        self.fileExitAction.setText(_translate("panicQL", "E&xit", None))
        self.fileExitAction.setIconText(_translate("panicQL", "Exit", None))
        self.editCutAction.setText(_translate("panicQL", "Cu&t", None))
        self.editCutAction.setIconText(_translate("panicQL", "Cut", None))
        self.viewHeaderAction.setText(_translate("panicQL", "&Header", None))
        self.viewHeaderAction.setIconText(_translate("panicQL", "Copy", None))
        self.viewImageAction.setText(_translate("panicQL", "&Paste", None))
        self.viewImageAction.setIconText(_translate("panicQL", "Paste", None))
        self.editFindAction.setText(_translate("panicQL", "&Find...", None))
        self.editFindAction.setIconText(_translate("panicQL", "Find", None))
        self.helpIndexAction.setText(_translate("panicQL", "&Index...", None))
        self.helpIndexAction.setIconText(_translate("panicQL", "Index", None))
        self.helpIndexAction.setShortcut(_translate("panicQL", "F1", None))
        self.new_menudAction.setText(_translate("panicQL", "Master Dark", None))
        self.new_menudAction.setIconText(_translate("panicQL", "Master Dark", None))
        self.calibrationsMaster_FlatAction.setText(_translate("panicQL", "Master Dome-Flat", None))
        self.calibrationsMaster_FlatAction.setIconText(_translate("panicQL", "Master Dome-Flat", None))
        self.calibrationsMaster_Sky_FlatAction.setText(_translate("panicQL", "Master Sky-Flat", None))
        self.calibrationsMaster_Sky_FlatAction.setIconText(_translate("panicQL", "Master Sky-Flat", None))
        self.toolsIRAF_consoleAction.setText(_translate("panicQL", "IRAF console", None))
        self.toolsIRAF_consoleAction.setIconText(_translate("panicQL", "IRAF console", None))
        self.toolsIRAF_consoleAction.setShortcut(_translate("panicQL", "Shift+I", None))
        self.toolsDS9_displayAction.setText(_translate("panicQL", "DS9 display", None))
        self.toolsDS9_displayAction.setIconText(_translate("panicQL", "DS9 display", None))
        self.toolsDS9_displayAction.setShortcut(_translate("panicQL", "Ctrl+D", None))
        self.toolsAladinAction.setText(_translate("panicQL", "Aladin", None))
        self.toolsAladinAction.setIconText(_translate("panicQL", "Aladin", None))
        self.toolsAladinAction.setShortcut(_translate("panicQL", "Ctrl+A", None))
        self.fileSearchAction.setIconText(_translate("panicQL", "Action", None))
        self.fileSearchAction.setToolTip(_translate("panicQL", "Search files", None))
        self.quitAction.setIconText(_translate("panicQL", "Action", None))
        self.quitAction.setToolTip(_translate("panicQL", "Quit Quick-Look", None))
        self.irafConsoleAction.setIconText(_translate("panicQL", "Action", None))
        self.irafConsoleAction.setToolTip(_translate("panicQL", "Open an IRAF console", None))
        self.irafConsoleAction.setShortcut(_translate("panicQL", "Shift+I", None))
        self.actionAbout.setText(_translate("panicQL", "About", None))
        self.actionAladin.setText(_translate("panicQL", "Aladin", None))
        self.actionAladin.setToolTip(_translate("panicQL", "Open Aladin application", None))
        self.actionAladin.setShortcut(_translate("panicQL", "Ctrl+A", None))

import panicQL_resources_rc
